cigionline/static/css/_global.scss
This isn't in our current site - it's leftover from when Foundation was installed here. Removing it so the font rendering looks the same.
=> Remove font smoothing

people/fixtures/people.json, people/models.py, people/tests.py, templates/people/person_list_experts_page.html, templates/people/person_list_leadership_page.html, templates/people/person_list_staff_page.html
Queried for person pages in the context rather than in a property. This allows us to check for a `show` query param to display different results on the leadership page.
=> Update person list page templates to use context

publications/models.py, templates/publications/publication_list_page.html
Initial query for publications table.
Here's my plan for these tables:
1. Query data with pagination (this PR), so that we can start styling the rows.
2. Add topics & types filters, also using query parameters like pages.
3. Update page and filter queries to use Ajax (https://learnwagtail.com/tutorials/wagtail-ajax-templates/). This will require some Javascript to replace the table rows and update the query parameters in the URL without reloading the whole page.
=> Query table rows for publications page

careers/models.py, careers/tests.py, core/models.py, core/tests.py
Initial part for CIGIHub/cigi-tickets#231
The "Why CIGI?" and "Why Waterloo?" pages exist at `/careers/why-cigi` and `/careers/why-waterloo`, respectively. This PR simply allows those pages to be created as children of the Careers page, which is an instance of `JobPostingListPage`.
=> Allow BasicPage as child of JobPostingListPage

package-lock.json, package.json, webpack.config.js
Upgraded webpack to 5.10.3. webpack 5 introduced a number of breaking changes, but the only one that affected us was replacing the deprecated `xtract-text-webpack-plugin` package with `mini-css-extract-plugin`.
=> Upgrade webpack to 5.10.3

.github/workflows/django.yml, package.json
Updating the build script from `npm run build:prod` to `npm build`. When deploying on Heroku, the node buildpack will run `npm build` during its setup. The idea here is to add the node buildpack before the Django buildpack so the webpack assets are built before Django is deployed.
=> Update build script to default npm build

cigionline/static/css/includes/_hero_article.scss, cigionline/static/css/includes/_hero_publication.scss, cigionline/static/css/layout/_sections.scss
The content pages are starting to look too spaced out in some instances because of the margin added to `<section>` tags. Removed the global margin and added it to the few places where we need it.
=> Remove margins from sections

templates/articles/article_landing_page.html, templates/articles/article_page.html, templates/base.html, templates/events/event_list_page.html, templates/events/event_page.html, templates/multimedia/multimedia_list_page.html, templates/multimedia/multimedia_page.html, templates/publications/publication_list_page.html, templates/publications/publication_page.html, templates/themes/ai_series/article_page.html, templates/themes/ai_series/multimedia_page.html, templates/themes/big_tech_s3/article_page.html, templates/themes/big_tech_s3/multimedia_page.html, templates/themes/data_series/article_page.html, templates/themes/data_series/multimedia_page.html, templates/themes/innovation_series/article_page.html, templates/themes/innovation_series/multimedia_page.html, templates/themes/longform/article_page.html
resolves CIGIHub/cigi-tickets#323
Updated the scripts to use defer rather than async, so that they get executed after the DOM is fully parsed. Also removed some scripts, since some webpack bundles only contain CSS (such as `articlePage`).
=> Fix script execution and clean up empty script tags

.flake8, cigionline/static/themes/longform/css/_longform_article_series.scss, cigionline/static/themes/longform/css/longform.scss, streams/blocks.py, templates/themes/longform/article_series_page.html, templates/themes/longform/streams/opinion_series_paragraph_block.html
resolves CIGIHub/cigi-tickets#334
This includes the first implementation of a themed StreamField block. I expanded the condition to check for both theme and page type, since in this case I needed the paragraphs in the article series page to be in the large container but the regular article page to be in the small container.
=> Style body section for Longform article series page

cigionline/static/themes/data_series/css/_article_page.scss
resolves CIGIHub/cigi-tickets#318
tweaking and cleaning up h3 styling
Tested on staging of live server, there doesn't appear to be styling for h2 or h4 for the data series.
=> cigi-318 - revisit and clean up h3 styling

cigionline/static/css/cigionline.scss, cigionline/static/css/includes/features/_feature_expert_short.scss, cigionline/static/css/layout/_home.scss, home/models.py, templates/home/home_page.html, templates/includes/features/feature_expert_short.html
Part of CIGIHub/cigi-tickets#411
This is just the initial step, adding the section and creating a featured expert include. I realized I can't yet query for Latest Activity - as the authors are added in StreamFields. I'm going to change this to have authors be another table that can be queried on.
Full:
Mobile:
=> Create experts section for home page

cigionline/static/css/includes/features/_feature_expert_short.scss, templates/includes/features/feature_content_large.html, templates/includes/features/feature_content_medium.html, templates/includes/features/feature_content_people.html, templates/includes/features/feature_content_small.html, templates/includes/features/feature_expert_short.html
resolves CIGIHub/cigi-tickets#411
Building on the experts section that was added in #790, this adds the latest activity section now that we can query content pages from the expert as a result of #797.
Full:
Mobile:
=> Add latest activity to experts section on home page

templates/publications/publication_page.html
resolves CIGIHub/cigi-tickets#424
Added as a full container since the Issuu only supports double page embeds through oEmbed.
=> Add Issuu oEmbed to publication page

cigionline/static/js/components/SearchTable.js
React component crashes when trying to initiate another search after a search that returned no results, when the window attempts to scroll to the ref that wasn't added to the no results paragraph.
=> Fix search table crashing after a no results query

cigionline/static/css/includes/_hero_publication_book.scss, templates/includes/editors.html
resolves CIGIHub/cigi-tickets#490
=> Remove extra spaces around editors names on publication hero

cigionline/static/pages/publication_page/css/publication_page.scss, templates/publications/publication_page.html
resolves CIGIHub/cigi-tickets#499
- Hide issuu embed for screens < 567px
Test: http://127.0.0.1:8000/publications/managed-retreat-high-risk-flood-areas-design-considerations-effective-property-buyout/
=> Hide issuu embed on mobile

articles/models.py
resolves CIGIHub/cigi-tickets#520
=> CIGI-520: Limit article landing page slider to 10 items

cigionline/static/css/global/_global.scss, cigionline/static/css/includes/_top_bar.scss
resolves CIGIHub/cigi-tickets#524
- Remove focus box shadow from search input
- Change dropdown search input background to black
=> CIGI-524: Adjust search input text focus and background color

cigionline/static/css/cigionline.scss, cigionline/static/css/global/_mixins.scss
resolves CIGIHub/cigi-tickets#404
- Moved bootstrap import to main scss file
=> CIGI-404: Move bootstrap css to global scss file

annual_reports/models.py, articles/models.py, careers/models.py, core/models.py, events/models.py, multimedia/models.py, newsletters/models.py, people/models.py, publications/models.py, research/models.py, subscribe/models.py
resolves CIGIHub/cigi-tickets#558
This issue was caused by certain page classes inheriting from multiple classes that have `search_fields` defined, which led to the subclasses only inheriting the variable from one of the superclasses. 
See https://github.com/wagtail/wagtail/issues/4940
=> CIGI-558: Fix ContentType null pointer error on admin search

cigionline/static/pages/person_page/index.js, people/search_expert.py
resolves CIGIHub/cigi-tickets#559
- Also fixed react proptype error
=> CIGI-559: Add multimedia page to expert activity search

config/nginx.conf.erb
Now that the static assets are fingerprinted in production, the files should never change. Thus, we can set the cache to a year as defined in [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt):
```
To mark a response as "never expires," an origin server sends an Expires date approximately one year from the time the response is sent. HTTP/1.1 servers SHOULD NOT send Expires dates more than one year in the future.
```
=> Increase production static asset cache to 1 year

cigionline/static/js/components/SearchTable.js, search/views.py
resolves CIGIHub/cigi-tickets#567
- This only applies to search page, as all other search components should be populated with initial data
=> CIGI-567: Return empty result if searchpage and searchtest is empty

articles/models.py, events/models.py, home/models.py, multimedia/models.py, templates/articles/article_landing_page.html, templates/events/event_list_page.html, templates/home/home_page.html, templates/multimedia/multimedia_list_page.html
Refactored the featured queries on the Opinions, Multimedia, and Events pages to match the optimizations done to the home page in #1170.
See the before/after table for response time and queries. Note that the home page was only optimized to update the promotion blocks query, which resulted in removing just a single query.
Page | Before - Time | Before - Queries | After - Time | After - Queries
--- | --- | --- | --- | ---
Home | 10714.93ms | 175 queries in 265.54ms | 10397.40ms | 174 queries in 271.81ms
Opinions | 9065.69ms | 183 queries in 217.63ms | 5820.57ms | 111 queries in 116.16ms
Multimedia | 2664.04ms | 54 queries in 58.63ms | 1853.61ms | 34 queries in 51.02ms
Events | 4101.96ms | 31 queries in 178.17ms | 1463.13ms | 22 queries in 39.37ms
=> Refactor featured queries

research/templatetags/topic_tags.py, templates/includes/recommended.html
The highlighted topics in the footer is a chunk of the queries on any given page - the majority just querying the correct URL to link with `{% pageurl %}. I added the request context to the template so that the `pageurl` template tag doesn't have to query for the default site. See the table below for response times on an article page. Note that these response times are quite high as I was testing with Django's dummy cache to get consistent results. Actual load times should be much smaller.
Page | Before - Time | Before - Queries | After - Time | After - Queries
--- | --- | --- | --- | ---
Article page | 8109.15ms | 106 queries in 253.61ms | 4850.56ms | 80 queries in 179.48ms
=> Add request context to highlighted topics template

cigionline/settings/dev.py, core/models.py, publications/models.py, templates/articles/article_page.html, templates/events/event_page.html, templates/includes/about_the_author.html, templates/includes/heroes/hero_event.html, templates/includes/heroes/hero_publication_book.html, templates/publications/publication_page.html, templates/themes/cyber_series/article_page.html
We can query the number of authors multiple times for a single request. This changes that to use a cached property instead.
=> Use cached property instead of counting authors

templates/includes/heroes/hero_event.html
resolves CIGIHub/cigi-tickets#578
- this spaces out the speakers slightly
=> CIGI-578: Use li instead of div for event hero speakers list

config/nginx.conf.erb
This header is overwritten by Cloudflare now, so we don't need them in our nginx config.
=> Remove nginx Cache-Control headers

cigionline/settings/base.py
Getting a CSRF verification failed error when logging in to admin. I think it's because I removed the session config in #1333
=> Add session engine back to config

cigionline/static/css/includes/_top_bar.scss, cigionline/static/css/streams/_inline_video_block.scss, cigionline/static/pages/article_landing_page/css/article_landing_page.scss, cigionline/static/themes/ai_series/css/_ai_series_article.scss, streams/blocks.py, templates/streams/chart_block.html, templates/themes/ai_series/streams/opinion_block_quote_block.html
resolves CIGIHub/cigi-tickets#584
- AI series footnotes styling /articles/international-legal-regulation-autonomous-technologies
- AI series block quote should be wider than other body blocks /articles/renewing-multilateral-governance-age-ai/
- Chart block should be narrower than other body blocks /articles/renewing-multilateral-governance-age-ai/
- Inline video block not centered /articles/strengthening-planetary-protection-policies-second-space-age/
- Vertically centre menu buttons in top bar
- Opinion series sliders authors should have less columns at smaller screen sizes /opinions
=> CIGI-584: Styling fixes part 1

cigionline/static/js/components/SearchTable.js
Elevated results could also appear in the regular search results, so the key that was just based on the page id was being duplicated. React was then displaying an error for the duplicate key and the elevated search result remained on subsequent searches.
=> Fix duplicate ids in search listing for elevated results

people/management/commands/generate_person_image_renditions.py
The query was hitting the limit of 1000 people and wasn't generating images for older experts. Updated the query to filter people with images.
I also added the original image rendition for the high res image on the expert page.
=> Fix generate expert image renditions

cigionline/settings/base.py, cigionline/static/css/includes/_hero_multimedia.scss, cigionline/static/js/components/MultimediaListing.js, cigionline/static/pages/multimedia_list_page/index.js, embeds/finders/oembed.py
resolves CIGIHub/cigi-tickets#595
- Use audio icon for audio contentsubtype in multimedia landing page listing
- Added custom oembed finder to add rel=0 param. This limits recommended items to those from our youtube channel
- Increased sticky video player z-index so it covers menu bar
=> CIGI-595: Multimedia fixes

streams/blocks.py
resolves CIGIHub/cigi-tickets#605
- Fixed issue where newsletter advertisement block image doesn't use full image url
=> CIGI-605: Add complete url for newsletter advertisement block images

requirements.txt
Reverts CIGIHub/cigionline#1624
pylint 2.6.0 requires astroid<=2.5, >=2.4.0
=> Revert "Bump astroid from 2.5.6 to 2.6.2"

newsletters/models.py, streams/blocks.py, templates/newsletters/newsletter_html.html, templates/streams/newsletter/advertisement_block.html, templates/streams/newsletter/content_block.html, templates/streams/newsletter/featured_content_block.html
resolves CIGIHub/cigi-tickets#638
- add tracking url to every href in newsletter html_string
- remove the addition of tracking url from various other places (blocks)
- all links in the html_string, including in-line url and in-line reference to other pages in cigionline, should now have GA tracking
---
=> CIGI-638: move the addition of tracking url to html_string

templates/newsletters/newsletter_html.html, templates/streams/newsletter/advertisement_block.html, templates/streams/newsletter/content_block.html, templates/streams/newsletter/featured_content_block.html, templates/streams/newsletter/social_block.html, templates/streams/newsletter/text_block.html
resolves CIGIHub/cigi-tickets#641
This changes font-family of newsletter templates from `font-family:futura-pt, Arial, sans-serif` to `font-family:Helvetica, Arial, sans-serif`, affecting both newsletter pages as well as their html string for export.
---
=> CIGI-641: change futura-pt to Helvetica in newsletter templates

events/models.py
resolves CIGIHub/cigi-tickets#639
This affects timezone **labels** from:
- one of the dropdown options
- default value when none selected
event timezone values remain unchanged - calendar functions unaffected.
---
=> CIGI-639: change hyphen to en-dash in timezone labels

templates/newsletters/newsletter_html.html, templates/streams/newsletter/advertisement_block.html
resolves CIGIHub/cigi-tickets#666
- Add check for ad block title field and don't render table if title is empty
- Add top margin to footer
---
=> CIGI-666: Newsletter spacing adjustments

core/templatetags/core_tags.py, templates/people/person_page.html
resolves CIGIHub/cigi-tickets#681
- created tag to determine if any in a list of values, casted as str, belong to another provided list
- add condition to display high-res link: must be of 'Expert', 'Management Team', or 'Board Member' person_types
---
=> CIGI-681: require specific person_types to show high-res

cigionline/static/pages/home_page/css/_home_page.scss, home/models.py, templates/home/home_page.html
resolves CIGIHub/cigi-tickets#684
- Relax block limit on home page
- Add class to make wide and podcast blocks take up entire container width
- Add margin bottom
---
=> CIGI-684: Allow multiple rows of promotion blocks on home page

cigionline/static/css/includes/features/_feature_publication_teaser.scss, cigionline/static/pages/home_page/css/_home_page.scss, templates/home/home_page.html, templates/includes/features/feature_publication_teaser.html
resolves CIGIHub/cigi-tickets#705
- Fixed main feature and featured multimedia sections' `<hr>` element (right after the big featured item) width on small screens
- Fixed featured publications containers overflowing on medium screens 
---
=> CIGI-705: Fix home page ar width, and featured publications overflow

cigionline/settings/production.py
resolves CIGIHub/cigi-tickets#721
Ever since the migration to Wagtail, CIGIOnline has had image loading issues that returned 500 errors. Research indicated that this may be an issue with Wagtail's rendition process where multiple concurrent requests for images that don't have existing renditions will clog Heroku dynos, leading to time out. 
Previously we generated renditions manually in order to bypass this issue, and although it helped decrease occurrences, the core issue was never resolved.
This change adds additional settings that may allow redis to better cache the image renditions.
---
This checklist should be completed if applicable before …
=> CIGI-721: Improve image rendition caching

articles/wagtail_hooks.py, cigionline/settings/base.py, core/models.py, requirements.txt, templates/articles/article_page.html
resolves CIGIHub/cigi-tickets#722
- Added adv_cache_tag package in order to pass dynamic cache key into cache tag
- Use cache key that includes article id, article type and article series id for articles. This allows cache clearing of individual articles as well as all articles belonging to a specific series
- In order to test this locally, redis will need to be installed, and wagtail configured to use the local redis server
---
=> CIGI-722: Add adv_cache_tag and use granular cache key for articles

articles/models.py
resolves CIGIHub/cigi-tickets#736
This resolves a drafttail editor crash caused by using both anchors and links in the footnotes section. The anchor button was removed to reduce confusion.
---
=> CIGI-736: Remove anchor tag from footnotes

signals/apps.py
- add host label to email subject and slack title
- add hyperlink of page
- use NOTIFICATIONS_ON flag to determine whether to send email, instead of relying on built-in debug flag.
Please test:
- host labels reflect the correct environment
- hyperlinks bring to the correct page
- email is not sending on staging when `NOTIFICATIONS_ON` variable is toggled False
=> CIGI-760c: publishing notification hyperlink and host

core/wagtail_hooks.py
resolves CIGIHub/cigi-tickets#769
- Changed go_live_at datetimepicker options to every 30 min
- Disabled input so editors cannot pick arbitrary time
---
=> CIGI-769: Limit editor go_live_at options

core/views.py
resolves CIGIHub/cigi-tickets#770
- defaulted the timeline api date to current year
- add query param support
To test: 
- visit `api/ar_timeline_pages/` to get list of pages for the current year
- add query param 'year' to get list for other years - `api/ar_timeline_pages/?year=2021`
---
=> CIGI-770: Add query param and default date to annual reports timeline api

cigionline/static/css/components/SearchTable.scss, cigionline/static/js/components/SearchTable.js, cigionline/static/js/components/SearchTableExperts.js
resolves CIGIHub/cigi-tickets#776
- Remove search table filter options if there is only 1 option
- Fixed css bug where hovering over a sort option causes jitters
---
=> CIGI-776: remove search table sort filter if there is only 1 option

signals/apps.py
resolves CIGIHub/cigi-tickets#780
- First publish now identified by counting publishes since the latest unpublish event, filtered by its timestamp
- Those without an unpublish event behave as previously
Please test cases:
1. first publish; no unpublish history. Expecting: "first: True" in logs
2. republish; no unpublish history. Expecting: "first: False" in logs
3. unpublished once; first publish since. Expecting: "first: True" in logs
4. unpublished more than once; first publish since. Expecting: "first: True" in logs
5. unpublished once; republish since. Expecting: "first: False" in logs
---
This checklist should be completed if applicable before …
=> CIGI-780: Update first-publish identification for purpose of publishing notifications

signals/apps.py
resolves CIGIHub/cigi-tickets#795
3 trigger types:
- "scheduled" - when `revision.approved_go_live_at` is populated and the timestamp is within 1hr of the latest published timestamp
- "scheduling" - when `revision.approved_go_live_at` is populated but not the second condition above
- "manual" - when `revision.approved_go_live_at` is **not** populated
=> CIGI-795: update logic to identify scheduling actions in Wagtail 4.0

streams/blocks.py, templates/streams/newsletter/content_block.html
resolves CIGIHub/cigi-tickets#833
- expand block text into html string
- target _a_ elements inside block text and add inline styling
- this allows targeting _a_ elements of internal links - which are normally stored as pseudo html strings whose elements are not targetable by BeautifulSoup _findall_ function; while avoids unwanted changes on title links.
---
=> CIGI-833: Fix to Newsletter internal links having different colour vs intended

cigionline/static/css/global/_global.scss, core/wagtail_hooks.py, streams/blocks.py
resolves CIGIHub/cigi-tickets#922
- added RTL styling option in richtext blocks
- currently deployed on staging: https://staging.cigionline.org/admin/pages/21175/edit/
---
=> CIGI-922: Right-to-left Language Support

templates/themes/freedom_of_thought/project_page.html
- patch updating the freedom of thought project page body label from "about the series" to "about"
=> CIGI-933c: update freedom of thought project page body label

research/templatetags/topic_tags.py
- update research page and footer to exclude topics with 0 count from being displayed
=> CIGI-980b: filter out topics with 0 count in research landing and footer

research/migrations/0039_alter_topic_tags.py, research/migrations/0040_update_themes.py, research/templatetags/topic_tags.py, research/tests.py, utils/helpers.py
resolves CIGIHub/cigi-tickets#984
- using `model.objects.create()` requires `path`, which can't just be any arbitrary string when there are required foreignkey fields (such as `article_type`) in the page model
- adding the page as a child to a parent page circumvents this problem with path
---
=> CIGI-984b: Highlighted topics query and tests update

templates/includes/features/feature_content_large.html
resolves CIGIHub/cigi-tickets#982
Specifically for allowing the FoT program page featured section to use gif as poster image, but change is on all large feature slots.
---
=> CIGI-982b: make large feature slot poster gif compatible

cigionline/settings/base.py, publications/models.py, templates/includes/heroes/hero_standard.html
resolves CIGIHub/cigi-tickets#986
- Add custom route to route /publications/essays to essays article type page
- Modify hero standard template to accomodate custom route
- To test: 
- move essay article type page back to /articles/
- rename it to "Essays"
- add essays to the publications menu if it's not there already, and add /publications/essays/ to the link_url field
Staged on staging site 2
---
=> CIGI-986: Move essay article type back to articles directory

cigionline/static/css/components/SearchTable.scss, templates/multimedia/multimedia_list_page.html
resolves CIGIHub/cigi-tickets#1000
- Add condition to not render promotion block on multimedia landing page if the field is empty
---
=> CIGI-1000: Do not render promotion block on multimedia landing page if empty

cigionline/static/pages/home_page/css/_home_page.scss, templates/home/home_page.html
resolves CIGIHub/cigi-tickets#1054
- Add padding to home page featured section when no banner is present
---
=> CIGI-1054: Add padding-top to homepage-featured when there is no banner

people/views.py
resolves CIGIHub/cigi-tickets#1074
- all_staff endpoint was built to only return the first 50 staff. Updated it to return all staff
---
=> CIGI-1074: Fix all_staff endpoint not requesting all staff members
