CIGIHub/cigionline

research/models.py
=> Limit richtext options on Topic pages

people/fixtures/staff.json, people/models.py, people/tests.py
Resolves CIGIHub/cigi-tickets#182
=> Filter staff page based on first letter of the last name

VagrantFile
Simple VagrantFile to have the same setup on PC, MAC, Windows.
=> Vagrantfile

people/models.py, people/tests.py
Thanks to @willmtl for the feedback on https://github.com/CIGIHub/cigionline/commit/ad4a13403f492df133a59d450770083ec1213866
=> Clean up staff page query and tests

cigionline/static/css/global/_variables.scss, cigionline/static/css/pages/_people.scss, templates/people/person_page.html
- Fixed display bug and added media queries
=> CIGI-197: Fix experts contact items display bug

people/tests.py, requirements.txt, research/tests.py
=> Update Wagtail to 2.11.2

cigionline/static/css/cigionline.scss, cigionline/static/css/streams/_autoplay_video_block.scss, templates/streams/autoplay_video_block.html
resolves CIGIHub/cigi-tickets#220
=> CIGI-220: Create autoplay video template

package-lock.json, package.json, webpack.config.js
We don't use this package, and I don't believe we'll need to.
=> Remove popper/core package

package-lock.json, package.json, webpack.config.js
Uninstalled the `url-loader` package and removed it from `webpack.config` as we're not using it.
=> Remove url-loader package

cigionline/static/themes/longform/css/_longform_article.scss
resolves CIGIHub/cigi-tickets#268
=> Style Longform About the Author section

cigionline/static/css/layout/_sections.scss, cigionline/static/pages/article_page/css/article_page.scss, templates/articles/article_page.html
resolves CIGIHub/cigi-tickets#286
=> Add works cited section to article pages

articles/models.py, careers/models.py, core/models.py, newsletters/models.py, people/models.py, publications/models.py, research/models.py, streams/blocks.py
=> Limit rich text features

templates/articles/article_landing_page.html, templates/articles/article_page.html, templates/base.html, templates/events/event_list_page.html, templates/events/event_page.html, templates/multimedia/multimedia_list_page.html, templates/multimedia/multimedia_page.html, templates/publications/publication_list_page.html, templates/publications/publication_page.html, templates/themes/big_tech_s3/article_page.html, templates/themes/big_tech_s3/multimedia_page.html, templates/themes/longform/article_page.html
Start downloading and executing scripts right away without waiting for DOM render.
=> Split bundles and move to head to add async scripts

cigionline/static/themes/innovation_series/css/_innovation_series_article.scss, cigionline/static/themes/innovation_series/css/_innovation_series_multimedia.scss, cigionline/static/themes/innovation_series/css/innovation_series.scss, cigionline/static/themes/innovation_series/index.js, streams/blocks.py, templates/themes/innovation_series/article_page.html, templates/themes/innovation_series/multimedia_page.html, templates/themes/longform/article_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#288
Created templates for article and multimedia pages.
=> Create templates and style body for Innovation series

cigionline/static/themes/innovation_series/css/_innovation_series_article.scss, templates/themes/innovation_series/article_page.html
resolves CIGIHub/cigi-tickets#289
=> Add hero section for Innovation series articles

cigionline/static/themes/innovation_series/css/_innovation_series_article.scss
resolves CIGIHub/cigi-tickets#291
=> Style "About the Author" section for Innovation series articles

cigionline/static/pages/article_page/css/article_page.scss, templates/articles/article_page.html
resolves CIGIHub/cigi-tickets#246
=> CIGI-246: Add truncated text for CIGI in the news

articles/models.py, cigionline/static/themes/ai_series/css/_ai_series_article.scss, cigionline/static/themes/ai_series/css/_ai_series_article_series.scss, cigionline/static/themes/ai_series/css/_ai_series_multimedia.scss, cigionline/static/themes/ai_series/css/ai_series.scss, cigionline/static/themes/ai_series/css/includes/_in_the_series.scss, cigionline/static/themes/ai_series/index.js, requirements.txt, templates/themes/ai_series/article_page.html, templates/themes/ai_series/article_series_page.html, templates/themes/ai_series/includes/in_the_series.html, templates/themes/ai_series/multimedia_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#296
=> Set up templates for AI series theme

cigionline/static/themes/data_series/css/_article_page.scss, cigionline/static/themes/data_series/css/_article_series_page.scss, cigionline/static/themes/data_series/css/_multimedia_page.scss, cigionline/static/themes/data_series/css/data_series.scss, cigionline/static/themes/data_series/css/includes/_in_the_series.scss, cigionline/static/themes/data_series/index.js, templates/themes/data_series/article_page.html, templates/themes/data_series/article_series_page.html, templates/themes/data_series/includes/in_the_series.html, templates/themes/data_series/multimedia_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#307
=> Set up templates for Data series theme

cigionline/static/themes/after_covid_series/css/_after_covid_series_article.scss, cigionline/static/themes/after_covid_series/css/_after_covid_series_article_series.scss, cigionline/static/themes/after_covid_series/css/_after_covid_series_multimedia.scss, cigionline/static/themes/after_covid_series/css/after_covid_series.scss, cigionline/static/themes/after_covid_series/index.js, templates/themes/after_covid_series/article_page.html, templates/themes/after_covid_series/article_series_page.html, templates/themes/after_covid_series/multimedia_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#324
=> Set up templates for After COVID series theme

articles/wagtail_hooks.py, cigionline/static/css/admin.css, cigionline/static/css/global/_global.scss, core/wagtail_hooks.py, streams/blocks.py
resolves CIGIHub/cigi-tickets#287
=> Implement drop caps in the Draftail editor

templates/publications/publication_page.html
resolves CIGIHub/cigi-tickets#338
=> Use rich text for publication series short description

cigionline/static/themes/ai_series/css/_ai_series_article_series.scss, templates/themes/ai_series/article_series_page.html, templates/themes/ai_series/includes/in_the_series.html
resolves CIGIHub/cigi-tickets#300
=> CIGI-300: Add styling for AI series article series page hero

cigionline/static/themes/longform/css/_longform_article.scss, cigionline/static/themes/longform/css/_longform_article_series.scss, templates/themes/longform/article_series_page.html
resolves CIGIHub/cigi-tickets#335
Full:
Mobile:
=> Implement "In the Series" section for Longform article series page

cigionline/static/css/global/_helpers.scss, cigionline/static/css/global/_mixins.scss, cigionline/static/css/includes/_authors.scss, cigionline/static/css/includes/_top_bar.scss, cigionline/static/index.js, cigionline/static/themes/ai_series/css/_ai_series_article_series.scss, cigionline/static/themes/health_security_series/css/_health_security_series_article.scss, cigionline/static/themes/health_security_series/css/_health_security_series_article_series.scss, cigionline/static/themes/health_security_series/css/_health_security_series_multimedia.scss, cigionline/static/themes/health_security_series/css/health_security_series.scss, cigionline/static/themes/health_security_series/index.js, cigionline/static/themes/longform/css/_longform_article.scss, cigionline/static/themes/longform/css/_longform_article_series.scss, templates/themes/health_security_series/article_page.html, templates/themes/health_security_series/article_series_page.html, templates/themes/health_security_series/multimedia_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#325
=> Set up templates for Health Security series

cigionline/static/css/includes/_footer.scss, cigionline/static/themes/innovation_series/css/_innovation_series_article_series.scss, cigionline/static/themes/innovation_series/css/innovation_series.scss, cigionline/static/themes/longform/css/_longform_article_series.scss, streams/blocks.py, templates/themes/innovation_series/article_series_page.html, templates/themes/innovation_series/streams/opinion_series_paragraph_block.html
resolves CIGIHub/cigi-tickets#339
resolves CIGIHub/cigi-tickets#341
Full:
Mobile:
=> Implement hero section on Innovation series article series page

cigionline/static/themes/innovation_series/css/_innovation_series_article_series.scss, templates/themes/innovation_series/article_series_page.html
resolves CIGIHub/cigi-tickets#340
Full:
Mobile:
=> Implement featured section on Innovation series article series page

cigionline/static/css/global/_mixins.scss, cigionline/static/css/global/_variables.scss, cigionline/static/themes/cyber_series/css/_cyber_series_article.scss, cigionline/static/themes/cyber_series/css/_cyber_series_article_series.scss, cigionline/static/themes/cyber_series/css/cyber_series.scss, cigionline/static/themes/cyber_series/index.js, streams/blocks.py, templates/themes/cyber_series/article_page.html, templates/themes/cyber_series/article_series_page.html, templates/themes/cyber_series/multimedia_page.html, templates/themes/cyber_series/streams/opinion_block_quote_block.html, templates/themes/cyber_series/streams/opinion_chart_block.html, templates/themes/cyber_series/streams/opinion_image_block.html, templates/themes/cyber_series/streams/opinion_series_paragraph_block.html, webpack.config.js
resolves CIGIHub/cigi-tickets#329
=> Set up templates for Cyber series

cigionline/static/themes/wto_series/css/_wto_series_article.scss, cigionline/static/themes/wto_series/css/_wto_series_article_series.scss, cigionline/static/themes/wto_series/css/_wto_series_multimedia.scss, cigionline/static/themes/wto_series/css/includes/_in_the_series.scss, cigionline/static/themes/wto_series/css/wto_series.scss, cigionline/static/themes/wto_series/index.js, templates/themes/after_covid_series/article_series_page.html, templates/themes/ai_series/article_series_page.html, templates/themes/data_series/article_series_page.html, templates/themes/health_security_series/article_series_page.html, templates/themes/innovation_series/article_series_page.html, templates/themes/longform/article_series_page.html, templates/themes/wto_series/article_page.html, templates/themes/wto_series/article_series_page.html, templates/themes/wto_series/includes/in_the_series.html, templates/themes/wto_series/multimedia_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#326
=> Set up templates for WTO series

cigionline/static/themes/women_and_trade_series/css/_women_and_trade_series_article.scss, cigionline/static/themes/women_and_trade_series/css/_women_and_trade_series_article_series.scss, cigionline/static/themes/women_and_trade_series/css/_women_and_trade_series_multimedia.scss, cigionline/static/themes/women_and_trade_series/css/includes/_in_the_series.scss, cigionline/static/themes/women_and_trade_series/css/women_and_trade_series.scss, cigionline/static/themes/women_and_trade_series/index.js, streams/blocks.py, templates/themes/women_and_trade_series/article_page.html, templates/themes/women_and_trade_series/article_series_page.html, templates/themes/women_and_trade_series/includes/in_the_series.html, templates/themes/women_and_trade_series/multimedia_page.html, templates/themes/women_and_trade_series/streams/opinion_series_paragraph_block.html, webpack.config.js
resolves CIGIHub/cigi-tickets#328
=> Set up templates for Women and Trade series

cigionline/static/themes/health_security_series/css/_health_security_series_article_series.scss, templates/themes/health_security_series/article_series_page.html
resolves CIGIHub/cigi-tickets#352
=> CIGI-352: Style Health Security series credits section

cigionline/static/css/streams/_block_quote_block.scss, cigionline/static/themes/health_security_series/css/_health_security_series_article.scss, cigionline/static/themes/health_security_series/css/health_security_series.scss, streams/blocks.py, templates/themes/health_security_series/article_page.html, templates/themes/health_security_series/article_series_page.html, templates/themes/health_security_series/multimedia_page.html, templates/themes/health_security_series/streams/opinion_block_quote_block.html
resolves CIGIHub/cigi-tickets#353
resolves CIGIHub/cigi-tickets#355
resolves CIGIHub/cigi-tickets#356
resolves CIGIHub/cigi-tickets#357
Test: /articles/pandemics-need-new-thinking-security/
=> CIGI-353, 355, 356, 357: Style Health Security series article page components 

articles/models.py, cigionline/static/themes/health_security_series/css/health_security_series.scss, cigionline/static/themes/health_security_series/css/includes/_in_the_series.scss, templates/themes/health_security_series/article_page.html, templates/themes/health_security_series/includes/in_the_series.html, templates/themes/health_security_series/multimedia_page.html
resolves CIGIHub/cigi-tickets#358
Test: /articles/pandemics-need-new-thinking-security/
=> CIGI-358: Implement Health Security in the series section

cigionline/static/css/cigionline.scss, cigionline/static/css/includes/features/_feature_content.scss, cigionline/static/css/layout/_home.scss, core/models.py, templates/core/home_page.html
resolves CIGIHub/cigi-tickets#406
=> Add featured section to home page

cigionline/static/css/cigionline.scss, cigionline/static/css/includes/features/_feature_publication_teaser.scss, cigionline/static/css/layout/_home.scss, home/models.py, templates/home/home_page.html, templates/includes/features/feature_publication_teaser.html
resolves CIGIHub/cigi-tickets#407
Full:
Mobile:
=> Add publications section to home page

cigionline/static/css/includes/features/_feature_content.scss, cigionline/static/css/includes/features/_feature_content_small.scss, cigionline/static/css/layout/_home.scss, home/models.py, templates/home/home_page.html, templates/includes/features/feature_content_large.html, templates/includes/features/feature_content_medium.html, templates/includes/features/feature_content_small.html
resolves CIGIHub/cigi-tickets#409
=> Add multimedia section to home page

cigionline/static/css/cigionline.scss, cigionline/static/css/streams/_embedded_video_block.scss, templates/streams/embedded_video_block.html
Needed to implement this block for CIGIHub/cigi-tickets#376, to display the embedded video on the page.
=> Implement embedded video block

templates/core/basic_page.html
=> Add hero image to basic page template

cigionline/static/css/layout/_tables.scss, templates/events/event_page.html
resolves CIGIHub/cigi-tickets#418
=> Add related files to the event pages

cigionline/static/themes/big_tech_s3/css/big_tech_s3.scss, cigionline/static/themes/data_series/css/_article_series_page.scss, templates/articles/article_page.html, templates/articles/media_landing_page.html, templates/core/basic_page.html, templates/core/funding_page.html, templates/core/privacy_notice_page.html, templates/events/event_page.html, templates/includes/body.html, templates/multimedia/multimedia_page.html, templates/people/person_list_experts_page.html, templates/people/person_list_leadership_page.html, templates/people/person_list_staff_page.html, templates/people/person_page.html, templates/publications/publication_page.html, templates/research/research_landing_page.html, templates/themes/big_tech_s3/multimedia_page.html, templates/themes/cyber_series/article_series_page.html, templates/themes/data_series/article_series_page.html, templates/themes/data_series/streams/opinion_series_paragraph_block.html
resolves CIGIHub/cigi-tickets#393
=> Add body to media landing page with new body include

articles/models.py, cigionline/static/pages/media_landing_page/css/media_landing_page.scss, cigionline/static/pages/media_landing_page/index.js, templates/articles/media_landing_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#394
Full:
Tablet:
Mobile:
=> Implement Latest section for Media Relations page

articles/models.py, cigionline/static/css/cigionline.scss, cigionline/static/css/includes/features/_feature_content_xlarge.scss, cigionline/static/pages/article_landing_page/css/article_landing_page.scss, cigionline/static/pages/article_landing_page/index.js, templates/articles/article_landing_page.html, templates/includes/features/feature_content_medium.html, templates/includes/features/feature_content_subtitle.html, templates/includes/features/feature_content_xlarge.html
resolves CIGIHub/cigi-tickets#419
=> Add featured content to opinions page

multimedia/models.py, publications/models.py, templates/articles/article_landing_page.html, templates/multimedia/multimedia_list_page.html
resolves CIGIHub/cigi-tickets#420
=> Add featured content to multimedia page

cigionline/static/pages/event_page/css/event_page.scss, templates/events/event_page.html
resolves CIGIHub/cigi-tickets#422
=> Add multimedia embed to event page

articles/models.py, articles/views.py, cigionline/static/css/components/ArticleSeriesListing.scss, cigionline/static/css/components/MultimediaListing.scss, cigionline/static/js/components/ArticleSeriesListing.js, cigionline/static/pages/article_series_list_page/index.js, cigionline/urls.py, templates/articles/article_series_list_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#396
=> Implement paginated table on Opinion Series page

cigionline/static/themes/cyber_series/css/_cyber_series_article.scss, cigionline/static/themes/cyber_series/css/cyber_series.scss
resolves CIGIHub/cigi-tickets#366
resolves CIGIHub/cigi-tickets#367
resolves CIGIHub/cigi-tickets#368
Styling for footnotes, works cited and about the author.
=> Cigi 366, 367, 368 - cyber series article page styles

menus/migrations/0002_populate_menus.py
Part of CIGIHub/cigi-tickets#425
=> Add Careers menu to populate menus migration

templates/careers/job_posting_list_page.html
resolves CIGIHub/cigi-tickets#426
=> Add body to careers page

careers/models.py, cigionline/static/css/global/_helpers.scss, cigionline/static/pages/job_posting_list_page/css/job_posting_list_page.scss, cigionline/static/pages/job_posting_list_page/index.js, templates/careers/job_posting_list_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#428
With job postings:
No job postings:
=> Add job postings to Careers page

templates/research/project_page.html
resolves CIGIHub/cigi-tickets#441
=> Create template for project pages

cigionline/static/themes/indigenous_lands_series/css/_indigenous_lands_series_article.scss, cigionline/static/themes/indigenous_lands_series/css/_indigenous_lands_series_article_series.scss, cigionline/static/themes/indigenous_lands_series/css/includes/_in_the_series.scss, cigionline/static/themes/indigenous_lands_series/css/indigenous_lands_series.scss, cigionline/static/themes/indigenous_lands_series/index.js, templates/themes/indigenous_lands_series/article_page.html, templates/themes/indigenous_lands_series/article_series_page.html, templates/themes/indigenous_lands_series/includes/in_the_series.html, webpack.config.js
resolves CIGIHub/cigi-tickets#330
=> Set up templates for Indigenous Lands series theme

articles/models.py, articles/views.py, cigionline/static/css/layout/_tables.scss, cigionline/static/js/components/ResearchContentListing.js, cigionline/static/js/components/SearchTable.js, cigionline/static/pages/research_landing_page/index.js, cigionline/urls.py, core/models.py, core/views.py, events/models.py, events/views.py, multimedia/models.py, multimedia/views.py, publications/models.py, templates/research/research_landing_page.html
resolves CIGIHub/cigi-tickets#398
=> Implement search table on Research page

core/templatetags/core_tags.py
I accidentally broke this when adding an existence check.
=> Fix page type template tag

cigionline/static/css/global/_variables.scss, cigionline/static/themes/after_covid_series/css/_after_covid_series_article.scss, cigionline/static/themes/after_covid_series/css/after_covid_series.scss, cigionline/static/themes/ai_series/css/_ai_series_article.scss, cigionline/static/themes/ai_series/css/_ai_series_article_series.scss, cigionline/static/themes/ai_series/css/ai_series.scss, cigionline/static/themes/big_tech_s3/css/_big_tech_s3_multimedia_series.scss, cigionline/static/themes/cyber_series/css/_cyber_series_article.scss, cigionline/static/themes/cyber_series/css/_cyber_series_article_series.scss, cigionline/static/themes/cyber_series/css/cyber_series.scss, cigionline/static/themes/cyber_series/css/includes/_in_the_series.scss, cigionline/static/themes/data_series/css/_article_page.scss, cigionline/static/themes/health_security_series/css/_health_security_series_article.scss, cigionline/static/themes/health_security_series/css/health_security_series.scss, core/templatetags/core_tags.py, package.json
The sass-lint test wasn't checking for SCSS in the themes directory.
=> Fix sass-lint check

cigionline/static/js/components/SearchTable.js, cigionline/static/js/components/TopicContentListing.js, cigionline/static/pages/publication_type_page/index.js, cigionline/static/pages/topic_page/index.js, templates/research/topic_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#466
=> Implement search table on topic page

cigionline/static/themes/women_and_trade_series/css/_women_and_trade_series_article.scss, templates/themes/women_and_trade_series/article_page.html
resolves CIGIHub/cigi-tickets#401
theming for woman and trade article hero
=> Cigi 401: Women and trade article hero

cigionline/static/themes/indigenous_lands_series/css/_indigenous_lands_series_article_series.scss, streams/blocks.py, templates/themes/indigenous_lands_series/article_series_page.html, templates/themes/indigenous_lands_series/includes/in_the_series.html, templates/themes/indigenous_lands_series/streams/opinion_series_paragraph_block.html
resolves CIGIHub/cigi-tickets#450
theming for about the series.
=> Cigi 450: indigenous lands about the series body block

cigionline/static/themes/indigenous_lands_series/css/_indigenous_lands_series_article_series.scss, cigionline/static/themes/indigenous_lands_series/css/indigenous_lands_series.scss, templates/themes/indigenous_lands_series/article_series_page.html
resolves CIGIHub/cigi-tickets#449
styling for series hero
=> Cigi 449: Indigenous lands series hero

templates/includes/about_the_author.html
resolves CIGIHub/cigi-tickets#471
=> CIGI-471: Hide short bio for archived authors

cigionline/urls.py, events/feeds.py, requirements.txt, templates/includes/heroes/hero_event.html
resolves CIGIHub/cigi-tickets#349
=> CIGI-349: Implement iCal registration on event pages

Procfile
Will need to revert this before launch.
=> Use debug log level in Heroku

templates/multimedia/multimedia_page.html
resolves CIGIHub/cigi-tickets#484
=> CIGI-484: Fix multimedia page recommended article includes

cigionline/settings/dev.py, templates/articles/article_landing_page.html, templates/includes/footer.html, templates/includes/top_bar.html
I also disabled the Django debug toolbar for development. I left it installed to we can uncomment the settings if we need to inspect something. It was really slowing down development rendering.
=> Enable template fragment caching for header and footer

articles/models.py, cigionline/static/pages/person_page/css/person_page.scss, people/models.py, people/search.py, people/search_expert.py, people/views.py, templates/people/person_page.html
resolves CIGIHub/cigi-tickets#477
=> Add "In the News" section to expert pages

articles/models.py, cigionline/static/pages/article_series_list_page/index.js
resolves CIGIHub/cigi-tickets#487
=> Fix opinion series search table

templates/themes/big_tech_s3/multimedia_series_page.html
resolves CIGIHub/cigi-tickets#488
=> Add missing season/episode to Big Tech latest episode

cigionline/static/themes/big_tech_s3/css/_big_tech_s3_multimedia.scss, templates/themes/big_tech_s3/multimedia_page.html
resolves CIGIHub/cigi-tickets#489
=> Add season/episode to Big Tech S3 episodes

cigionline/static/themes/after_covid_series/css/includes/_in_the_series.scss
resolves CIGIHub/cigi-tickets#491
=> Fix COVID in the series section to be 4 columns

cigionline/static/themes/big_tech/css/_big_tech_multimedia.scss, cigionline/static/themes/big_tech_s3/css/_big_tech_s3_multimedia.scss
resolves CIGIHub/cigi-tickets#492
=> Fix Big Tech transcript button colour

templates/includes/heroes/hero_publication_book.html
resolves CIGIHub/cigi-tickets#493
=> Pluralize authors on book hero

cigionline/static/pages/funding_page/css/funding_page.scss, cigionline/static/pages/funding_page/index.js, templates/core/funding_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#461
=> Update Wagtail Funding page with 2020 data

cigionline/static/css/global/_mixins.scss, cigionline/static/themes/health_security_series/css/_health_security_series_article_series.scss, cigionline/static/themes/women_and_trade_series/css/_women_and_trade_series_article_series.scss, templates/themes/after_covid_series/article_page.html, templates/themes/after_covid_series/multimedia_page.html, templates/themes/ai_series/multimedia_page.html, templates/themes/cyber_series/multimedia_page.html, templates/themes/data_series/multimedia_page.html, templates/themes/health_security_series/article_page.html, templates/themes/health_security_series/multimedia_page.html, templates/themes/indigenous_lands_series/article_page.html, templates/themes/innovation_series/multimedia_page.html, templates/themes/women_and_trade_series/article_series_page.html, templates/themes/women_and_trade_series/multimedia_page.html, templates/themes/wto_series/multimedia_page.html
resolves CIGIHub/cigi-tickets#496
resolves CIGIHub/cigi-tickets#497
resolves CIGIHub/cigi-tickets#498
resolves CIGIHub/cigi-tickets#500
resolves CIGIHub/cigi-tickets#501
1. Hide topics list for light theme footer:
http://127.0.0.1:8000/multimedia/video-security-intelligence-and-global-health-crisis/
http://127.0.0.1:8000/global-cooperation-after-covid-19/
2. Add background colour for women and trade series page in the series section:
http://127.0.0.1:8000/reshaping-trade-through-womens-economic-empowerment/
3. Disable recommended block for most article/multimedia pages that belong to a series. I have tested the following:
Innovation
- http://127.0.0.1:8000/multimedia/video-rohinton-p-medhora-introduces-new-thinking-innovation/
- http://127.0.0.1:8000/articles/framing-innovation-strategy/ …
=> CIGI-496, 497, 498, 500, 501: Series articles/multimedia fixes

templates/publications/publication_page.html
resolves CIGIHub/cigi-tickets#509
=> Fix book trailer embed on publication page

cigionline/static/css/layout/_hero.scss, templates/includes/heroes/hero_standard.html
Part of CIGIHub/cigi-tickets#515
=> Fix styling for multiple hero links

templates/includes/heroes/hero_publication_book.html
resolves CIGIHub/cigi-tickets#510
=> CIGI-510: Lower case "by" in "Edited By" in book hero

cigionline/static/themes/women_and_trade_series/css/includes/_in_the_series.scss
resolves CIGIHub/cigi-tickets#523
=> Fix author style for Women and Trade in the series section

templates/people/person_page.html
resolves CIGIHub/cigi-tickets#536
=> Show expert content on archived expert pages

templates/themes/wide_landscape/article_page.html
resolves CIGIHub/cigi-tickets#537
=> Implement Wide Landscape article theme

cigionline/static/css/includes/_top_bar.scss
resolves CIGIHub/cigi-tickets#539
=> Increase top bar menu font size

cigionline/settings/base.py, cigionline/static/css/components/CookieConsent.scss, cigionline/static/css/global/_variables.scss, cigionline/static/index.js, cigionline/static/js/components/CookieConsent.js, cigionline/urls.py, core/views.py, templates/base.html
resolves CIGIHub/cigi-tickets#535
=> Implement cookie consent banner

cigionline/static/themes/data_series/css/_article_series_page.scss
resolves CIGIHub/cigi-tickets#540
=> Fix hero position for Data Series article series page

cigionline/static/css/global/_mixins.scss
resolves CIGIHub/cigi-tickets#541
=> Fix mobile/large CIGI logo fill colour

templates/articles/article_page.html, templates/includes/features/feature_content_large.html, templates/includes/features/feature_content_medium.html, templates/includes/features/feature_content_xlarge.html, templates/includes/features/feature_poster_teaser.html, templates/includes/promotion_block.html, templates/includes/swiper.html, templates/streams/image_block.html, templates/themes/after_covid_series/article_series_page.html, templates/themes/after_covid_series/includes/in_the_series.html, templates/themes/ai_series/article_series_page.html, templates/themes/ai_series/includes/in_the_series.html, templates/themes/health_security_series/article_series_page.html, templates/themes/health_security_series/includes/in_the_series.html, templates/themes/longform_2/streams/opinion_image_block.html, templates/themes/wide_landscape/article_page.html, templates/themes/women_and_trade_series/article_page.html, templates/themes/wto_series/article_page.html, templates/themes/wto_series/article_series_page.html
Reverts CIGIHub/cigionline#1131
=> Revert "Try to remove gif template conditions to test performance"

templates/themes/after_covid_series/article_series_page.html, templates/themes/ai_series/article_series_page.html, templates/themes/cyber_series/article_series_page.html, templates/themes/data_series/article_series_page.html, templates/themes/health_security_series/article_series_page.html, templates/themes/indigenous_lands_series/article_series_page.html, templates/themes/innovation_series/article_series_page.html, templates/themes/longform/article_series_page.html, templates/themes/platform_governance_series/article_series_page.html, templates/themes/women_and_trade_series/article_series_page.html, templates/themes/wto_series/article_series_page.html
resolves CIGIHub/cigi-tickets#547
=> Add description and image metadata to article series pgaes

templates/includes/heroes/hero_standard.html
resolves CIGIHub/cigi-tickets#548
=> CIGI-548: Hide submenu label if there are no items

cigionline/static/css/global/_helpers.scss, cigionline/static/js/components/ArticleListingSimple.js, cigionline/static/js/components/PublicationListingSimple.js, cigionline/static/pages/article_type_page/index.js, cigionline/static/pages/publication_type_page/index.js
resolves CIGIHub/cigi-tickets#549
=> CIGI-549: Change publication type label to singular

cigionline/static/css/layout/_hero.scss
resolves CIGIHub/cigi-tickets#556
=> CIGI-556: Increase hero subtitle line-height

people/search_expert.py, templates/includes/features/feature_expert_short.html
resolves CIGIHub/cigi-tickets#550
=> CIGI-550: Experts latest activities - add download button and limit content types

cigionline/settings/base.py, cigionline/static/js/components/ResearchContentListing.js, cigionline/static/pages/research_landing_page/index.js
resolves CIGIHub/cigi-tickets#516
- Increased max result window to 13000 to accomodate large results quantity on research page and main search page
- Limited research page search table content types
=> CIGI-516: Fix research page search issue

cigionline/static/js/components/SearchTable.js
resolves CIGIHub/cigi-tickets#554
- Resolves bug with search table where currentPage state interferes with search due to it setting an offset
- Reset currentPage on search submit
=> CIGI-554: Fix search table current page bug

cigionline/settings/production.py
=> Use ManifestStaticFilesStorage in production to hash static assets

templates/includes/features/feature_expert_short.html
resolves CIGIHub/cigi-tickets#561
=> CIGI-561: Remove duplicate db calls

templates/home/home_page.html
resolves CIGIHub/cigi-tickets#562
- Caching swiper reduced queries by ~100
=> CIGI-562: Add cache to home page swiper

cigionline/static/js/components/Paginator.js
resolves CIGIHub/cigi-tickets#566
- Fixed issue with page numbers not sorting correctly
=> CIGI-566: Fix paginator sort

cigionline/static/css/includes/_top_bar.scss, cigionline/static/index.js, templates/includes/top_bar.html
resolves CIGIHub/cigi-tickets#565
- Added overflow: scroll and increased inner container height to accomodate
- Removed accordion icon if there are no submenu items
- Adjust js so opening menu will close search, and vice versa
=> CIGI-565: Main drop down menu improvements

templates/articles/article_landing_page.html, templates/articles/article_page.html, templates/home/home_page.html, templates/publications/publication_list_page.html, templates/publications/publication_page.html
Caching as much content as possible:
Page |After cache Queries - Before | After cache Queries - after
--- | --- | ---
Home | 106 queries in 93.54ms | 45 queries in 54ms
Opinions | 46 queries in 43ms | 28 queries in 14ms
Publication List | 47 queries in 23ms | 15 queries in 11ms
Publication | 46 queries in 21ms | 21 queries in 10ms
=> Use Template fragment caching

newsletters/models.py, streams/blocks.py
resolves CIGIHub/cigi-tickets#574
- Added check to not perform string replacement if rendering to html string
=> CIGI-574: Fix newsletter event content block time duplication

cigionline/static/css/includes/features/_feature_content.scss, cigionline/static/css/includes/features/_feature_content_large.scss, cigionline/static/css/includes/features/_feature_publication_teaser.scss
resolves CIGIHub/cigi-tickets#576
Bring feature content title spacing more in line with styling on live site
=> CIGI-576: Adjust feature content title line height

cigionline/static/js/components/SearchTable.js, cigionline/static/pages/search_page/index.js
resolves CIGIHub/cigi-tickets#581
=> Set relevance as default for search table

templates/research/project_page.html
resolves CIGIHub/cigi-tickets#587
=> CIGI-587: Add submenu to project page

core/models.py
resolves CIGIHub/cigi-tickets#590
=> CIGI-590: remove duplicates from content page recommended section

cigionline/static/js/components/ResearchContentListing.js, cigionline/static/js/components/SearchTable.js
resolves CIGIHub/cigi-tickets#591
- Fixed contenttype filter (it was including all contenttypes in the query)
- Display row contentsubtype if it exists
=> CIGI-591: Research search table fixes

cigionline/settings/production.py, templates/themes/women_and_trade_series/multimedia_page.html
=> Add default from email

cigionline/settings/production.py
=> Add default from email part 2

streams/blocks.py
resolves CIGIHub/cigi-tickets#593
- replace admin url with site root url
- remove period after May
=> CIGI-593: Newsletter fixes

streams/blocks.py
resolves CIGIHub/cigi-tickets#593
- Previous replacement fix didn't work due to image_url being a relative url. Changed this to dynamically build image_url
=> CIGI-593: Newsletter image url fix

cigionline/settings/base.py
=> Update admin base_url

templates/events/event_page.html, templates/includes/heroes/hero_event.html
resolves CIGIHub/cigi-tickets#596
- Add check so registration and calendar buttons don't show up on past event pages
=> CIGI-596: Event page fix

menus/migrations/0002_populate_menus.py
=> Add gender topic menu

streams/blocks.py
resolves CIGIHub/cigi-tickets#599
- Use full_url for content links because switching to two sites made it include the host as well
- Use beautifulsoup to parse and html and prepend event info. This is because the new wagtail streamfields add a data- property, which broke our earlier replacement code
=> Use full_url for content links and use beautiful soup to add event info

streams/blocks.py
resolves CIGIHub/cigi-tickets#599
- Django datetimefield stores time as UTC, which needs to be converted
=> CIGI-599: Fix newsletter event time zone issue

streams/blocks.py, templates/newsletters/newsletter_html.html, templates/streams/newsletter/advertisement_block.html, templates/streams/newsletter/content_block.html, templates/streams/newsletter/featured_content_block.html, templates/streams/newsletter/social_block.html, templates/streams/newsletter/text_block.html
resolves CIGIHub/cigi-tickets#599
- In the drupal newsletter, links are styled through a string replacement.
=> CIGI-599: Add newsletter styled link

streams/blocks.py
resolves CIGIHub/cigi-tickets#603
- Added check for newsletter block to only take short_description if content type is opinion or publication
=> CIGI-603: Fix newsletter short_description null pointer

streams/blocks.py
resolves CIGIHub/cigi-tickets#605
=> CIGI-605: Update mailchimp icon urls

streams/blocks.py
resolves CIGIHub/cigi-tickets#604
- Add inline styling to links
=> CIGI-604: Add inline styling to newsletter text links

config/nginx.conf.erb
resolves CIGIHub/cigi-tickets#606
=> CIGI-606: Add 2021 annual report nginx proxy settings

streams/blocks.py, templates/streams/newsletter/social_block.html, templates/streams/newsletter/text_block.html
resolves CIGIHub/cigi-tickets#609
- Add inline styling to newsletter recommended and text blocks
=> CIGI-609: Fix newsletter text block and social block link styling

templates/annual_reports/annual_report_page.html
resolves CIGIHub/cigi-tickets#614
- Use file url instead of field property
=> CIGI-614: Use file urls for annual report page reports

cigionline/static/js/components/TwentiethPage.js, cigionline/static/pages/twentieth_page/css/twentieth_page.scss, templates/core/twentieth_page.html
resolves CIGIHub/cigi-tickets#607
- Removed gallery caption on big screens
- Added social image support
=> CIGI-607: Remove gallery caption for desktop; add support for og image

cigionline/static/pages/twentieth_page/css/twentieth_page.scss
resolves CIGIHub/cigi-tickets#607
- Show year for gallery images
- Added hover effect for gallery nav
=> CIGI-607c: Hide gallery text only and add hover effect to timeline nav

cigionline/static/js/components/Portal.js, cigionline/static/js/components/TwentiethPage.js, cigionline/static/js/components/TwentiethPageNavArrows.js, cigionline/static/js/components/TwentiethPageSlide.js, cigionline/static/js/components/TwentiethPageSlide1Content.js, cigionline/static/js/components/TwentiethPageSlide2Content.js, cigionline/static/js/components/TwentiethPageSlide3Content.js, cigionline/static/js/components/TwentiethPageSlide4Content.js, cigionline/static/js/components/TwentiethPageSlide5Content.js, cigionline/static/pages/twentieth_page/css/twentieth_page.scss, cigionline/static/pages/twentieth_page/index.js, core/models.py, core/tests.py
resolves CIGIHub/cigi-tickets#618
=> CIGI-618: Resolve 20th react page linter errors

cigionline/static/pages/twentieth_page_singleton/css/twentieth_page_singleton.scss, cigionline/static/pages/twentieth_page_singleton/index.js, templates/streams/timeline_gallery_block.html
- Centre arrows to slide dynamically
- Fix slide height for large screens
=> CIGI-619: Add dynamic repositioning of nav arrows

cigionline/static/pages/twentieth_page_singleton/css/twentieth_page_singleton.scss
=> CIGI-619: Fix typo

cigionline/static/pages/twentieth_page_singleton/css/twentieth_page_singleton.scss
=> CIGI-619: Hide disabled buttons

cigionline/static/pages/twentieth_page_singleton/css/twentieth_page_singleton.scss, cigionline/static/pages/twentieth_page_singleton/index.js
=> CIGI-619: Tweak padding offset

cigionline/static/pages/twentieth_page_singleton/css/twentieth_page_singleton.scss
=> CIGI-619: Bump nav font size

cigionline/static/pages/twentieth_page_singleton/css/twentieth_page_singleton.scss, cigionline/static/pages/twentieth_page_singleton/index.js
=> CIGI-619: Show only one slide on medium breakpoint

cigionline/static/themes/big_tech/css/big_tech.scss, cigionline/static/themes/big_tech_s3/css/big_tech_s3.scss
resolves CIGIHub/cigi-tickets#622
=> CIGI-622: Decrease bullet point font size on Big Tech articles

templates/base.html
resolves CIGIHub/cigi-tickets#615
=> CIGI-615: Update facebook appid

articles/models.py, cigionline/urls.py, core/views.py, templates/articles/article_page.html, templates/core/old_pages_list.html, templates/includes/features/feature_content_medium.html, templates/includes/recommended_article.html, templates/streams/recommended_block.html, templates/themes/big_tech/includes/recommended_article.html, templates/themes/big_tech_s3/includes/recommended_article.html, templates/themes/longform_2/streams/opinion_recommended_block.html
resolves CIGIHub/cigi-tickets#644
- Hide all images inside article and on recommended blocks if article is older than 2017
---
=> CIGI-644: Hide images if article is older than 2017

careers/models.py
resolves CIGIHub/cigi-tickets#651
- Place items without closing date on top
---
=> CIGI-651: Update careers page sort order

core/wagtail_hooks.py
resolves CIGIHub/cigi-tickets#652
- All page choosers are now sorted based on first_published_at field, with most recent on top
---
=> CIGI-652: Add sort hook

core/templatetags/core_tags.py, templates/people/person_page.html
resolves CIGIHub/cigi-tickets#653
Wrapping each meta block content within condition that the person is not archived
---
=> CIGI-653: Hide person's metadata from their page if they are archived

cigionline/static/themes/big_tech/css/big_tech.scss, cigionline/static/themes/big_tech_s3/css/big_tech_s3.scss, templates/themes/big_tech/includes/pocket_casts_icon.svg, templates/themes/big_tech_s3/includes/pocket_casts_icon.svg
resolves CIGIHub/cigi-tickets#669
---
=> CIGI-669: Fix BT subscribe dropdown overflow

cigionline/static/css/global/_global.scss, cigionline/static/css/includes/_top_bar.scss, cigionline/static/index.js, cigionline/static/js/create_sticky_header_scroll_listener.js, cigionline/static/themes/big_tech/css/_big_tech_multimedia.scss, cigionline/static/themes/big_tech/css/big_tech.scss, cigionline/static/themes/big_tech_s3/css/_big_tech_s3_multimedia.scss, cigionline/static/themes/big_tech_s3/css/big_tech_s3.scss, templates/includes/top_bar.html, templates/themes/big_tech/article_page.html, templates/themes/big_tech/includes/top_bar.html, templates/themes/big_tech/multimedia_page.html, templates/themes/big_tech_s3/article_page.html, templates/themes/big_tech_s3/includes/top_bar.html, templates/themes/big_tech_s3/multimedia_page.html, templates/themes/big_tech_s3/multimedia_series_page.html
resolves CIGIHub/cigi-tickets#675
- Add CIGI top bar to the following:
- big tech s3 multimedia series page
- big tech s3 multimedia page
- big tech s3 article page
- big tech multimedia page
- big tech article page
---
=> CIGI-675: Add CIGI top bar to Big Tech themed pages

cigionline/static/themes/big_tech_s3/css/_big_tech_s3_multimedia_series.scss
resolves CIGIHub/cigi-tickets#678
- Use boder top instead of border bottom in BT episode listing so if there is only one episode there will be no border
---
=> CIGI-678b: Move border bottom to border top

cigionline/static/themes/big_tech_s3/css/_big_tech_s3_multimedia_series.scss
resolves CIGIHub/cigi-tickets#678
---
=> CIGI-678c: temporarily Remove episode listing border bottom

cigionline/static/themes/big_tech_s3/css/_big_tech_s3_multimedia_series.scss
resolves CIGIHub/cigi-tickets#678
---
=> CIGI-678: revert border issue

cigionline/static/css/includes/_publications_featured_list.scss, templates/includes/publications_featured_list.html, templates/includes/topics.html
resolves CIGIHub/cigi-tickets#680
- Changed featured items template to be more in line with other featured items by using topics include
---
=> CIGI-680: Fix publications page featured section topics

cigionline/static/themes/big_tech/css/big_tech.scss, cigionline/static/themes/big_tech_s3/css/big_tech_s3.scss
resolves CIGIHub/cigi-tickets#679
---
=> CIGI-679: increase CIGI top bar font size for bt pages

home/models.py
resolves CIGIHub/cigi-tickets#683
- implement same logic as recommended content in home page featured experts
---
=> CIGI-683: Automatically populate home page featured experts

home/models.py
resolves CIGIHub/cigi-tickets#683
- Select experts randomly instead of first three
---
=> CIGI-683b: Select experts randomly

streams/blocks.py
resolves CIGIHub/cigi-tickets#690
- Add conditions to check for non-ContentPage pages to avoid null pointer errors
---
=> CIGI-690: Add conditions for non-content page pages

templates/includes/footer.html, templates/includes/top_bar.html, templates/includes/twentieth_page_top_bar.html, templates/themes/big_tech/includes/footer.html, templates/themes/big_tech_s3/includes/footer.html
resolves CIGIHub/cigi-tickets#696
---
=> CIGI-696: replace 20th logos to regular

templates/newsletters/newsletter_html.html
resolves CIGIHub/cigi-tickets#697
- Use original cigi logo for newsletter template
---
=> CIGI-697: Use original logo (not 20th) for newsletter

cigionline/static/themes/pfpc_series/css/_pfpc_series_article.scss, cigionline/static/themes/pfpc_series/css/pfpc_series.scss, cigionline/static/themes/pfpc_series/index.js, templates/themes/pfpc_series/article_page.html, templates/themes/pfpc_series/article_series_page.html, templates/themes/pfpc_series/multimedia_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#693
---
=> CIGI-693: add css and template for pfpc series

cigionline/static/themes/pfpc_series/css/_pfpc_series_article.scss, streams/blocks.py, templates/themes/pfpc_series/streams/opinion_chart_block.html
resolves CIGIHub/cigi-tickets#695
---
=> CIGI-695b: pfpc charts retain original size; scaled to width of paragraph

cigionline/static/css/includes/_top_bar.scss
resolves CIGIHub/cigi-tickets#699
- Decrease top bar small CIGI logo size
---
=> CIGI-699: Decrease top bar small CIGI logo size

cigionline/static/pages/article_series_page/css/article_series_page.scss
- group session items tighter; 
- remove space above author; 
- space between sessions larger
resolves CIGIHub/cigi-tickets#700
---
=> CIGI-700: adjust generic series landing page spacing

templates/includes/heroes/hero_event.html
resolves CIGIHub/cigi-tickets#701
- Added condition to not render registration and calendar buttons for private events
---
=> CIGI-701: Hide registration and calendar buttons for private events

cigionline/static/themes/pfpc_series/css/_pfpc_series_article.scss, templates/themes/pfpc_series/article_page.html
resolves CIGIHub/cigi-tickets#704
- centre article banner images
- series description reflected in article pages
---
=> CIGI-704b: further adjustments to PfPC series layout

cigionline/static/themes/pfpc_series/css/_pfpc_series_article_series.scss, cigionline/static/themes/pfpc_series/css/includes/_in_the_series.scss
resolves CIGIHub/cigi-tickets#706
---
=> CIGI-706: Decrease font weight for series labels

cigionline/static/themes/pfpc_series/css/_pfpc_series_article_series.scss, cigionline/static/themes/pfpc_series/css/includes/_in_the_series.scss
resolves CIGIHub/cigi-tickets#706
---
=> CIGI-706b: Decrease heading font weights

cigionline/static/themes/pfpc_series/css/_pfpc_series_article_series.scss, templates/articles/article_landing_page.html
resolves CIGIHub/cigi-tickets#707
- Fixed series page gradient issue on safari
- Adjusted padding  
- Refresh article landing page swiper cache on page save
---
=> CIGI-707: Fix PfPC styling issues

templates/themes/pfpc_series/article_series_page.html
resolves CIGIHub/cigi-tickets#710
- Display unpublished items without link
---
=> CIGI-710: Add support for unpublished items

cigionline/static/themes/pfpc_series/css/includes/_in_the_series.scss, templates/themes/pfpc_series/includes/in_the_series.html
resolves CIGIHub/cigi-tickets#712
- remove links from unpublished items
- fix gradient
---
=> CIGI-712: PfPC in the series section fixes

cigionline/static/js/components/SearchTableExperts.js, cigionline/static/pages/person_list_experts_page/index.js, people/views.py, templates/people/person_list_experts_page.html
resolves CIGIHub/cigi-tickets#613
---
=> CIGI-613: Use latest revision for all experts api call cache

cigionline/static/css/includes/features/_feature_publication_teaser.scss, templates/includes/features/feature_publication_teaser.html
resolves CIGIHub/cigi-tickets#718
- limit publication teaser template authors to 3 max
- add margin above authors 
---
=> CIGI-718: Limit publication teaser authors to 3

templates/annual_reports/annual_report_list_page.html, templates/home/home_page.html
resolves CIGIHub/cigi-tickets#719
- Updated home page featured events and annual reports page swiper template cache busting 
---
=> CIGI-719: Update cache-busting conditions

home/models.py
resolves CIGIHub/cigi-tickets#720
- Grab first 3 items of events list page featured events for home page featured events section
---
=> CIGI-720: Use event page featured events to populate home page featured events

articles/management/commands/publish_series_articles.py, articles/models.py, cigionline/static/themes/john_holmes_series/css/_john_holmes_series_article_series.scss, cigionline/static/themes/john_holmes_series/css/includes/_in_the_series.scss, cigionline/static/themes/john_holmes_series/css/john_holmes_series.scss, core/models.py, multimedia/models.py, newsletters/models.py, people/models.py, publications/models.py, research/models.py, templates/themes/john_holmes_series/includes/in_the_series.html
resolves CIGIHub/cigi-tickets#723
---
=> CIGI-723c: John Holmes series adjustments

cigionline/static/css/includes/features/_feature_content_xlarge.scss
resolves CIGIHub/cigi-tickets#732
---
=> CIGI-732: expand image of first featured item on opinions page

cigionline/static/pages/home_page/css/_home_page.scss, templates/home/home_page.html
=> Add additional cache keys to home page promotions

cigionline/static/pages/home_page/css/_home_page.scss, templates/home/home_page.html
=> Standardize home page section spacing

cigionline/static/pages/home_page/css/_home_page.scss, templates/home/home_page.html
=> Adjust home page spacing

cigionline/static/themes/john_holmes_series/css/_john_holmes_series_article_series.scss
resolves CIGIHub/cigi-tickets#735
---
=> CIGI-735: Show series short description for John Holmes series when screen is short

cigionline/static/themes/four_domains_series/css/_article_page.scss, templates/themes/four_domains_series/article_page.html
resolves CIGIHub/cigi-tickets#734
---
=> CIGI-734: Add series items description to article template

cigionline/static/themes/four_domains_series/css/_article_page.scss
resolves CIGIHub/cigi-tickets#734
---
=> CIGI-734: update block quote line colour

cigionline/static/themes/four_domains_series/css/_article_page.scss
resolves CIGIHub/cigi-tickets#734
---
=> CIGI-734: update blockquote colours

cigionline/static/css/components/CookieBanner.scss, cigionline/static/css/components/CookieConsent.scss, cigionline/static/css/global/_variables.scss, cigionline/static/index.js, cigionline/static/js/components/CookieBanner.js, cigionline/static/js/components/CookieConsent.js, templates/base.html, templates/includes/top_bar.html
resolves CIGIHub/cigi-tickets#744
---
=> CIGI-744: Implement top bar survey banner

templates/people/person_page.html
resolves CIGIHub/cigi-tickets#752
---
=> CIGI-752: add media contact to list that show high-res

.flake8, cigionline/settings/base.py, requirements.txt
resolves CIGIHub/cigi-tickets#750
- pip install -r requirements to install the package
- access the scheduled pages admin page through `Reports` -> `Scheduled pages`
---
=> CIGI-750: Add wagtailschedules package

cigionline/static/js/components/SearchResultListing.js
resolves CIGIHub/cigi-tickets#745
---
=> CIGI-745: Uncommon page types now have icon on search results listing

streams/blocks.py, templates/streams/newsletter/content_block.html
resolves CIGIHub/cigi-tickets#670
---
=> CIGI-670: Fix str error in newsletter content block

cigionline/static/index.js, streams/blocks.py, templates/includes/top_bar.html
resolves CIGIHub/cigi-tickets#754
removed:
- banner import
- references to the imported var 
- resulting empty container in template
---
=> CIGI-754: remove survey banner

research/models.py
resolves CIGIHub/cigi-tickets#755
- Adds (Archived) string to archived topics in admin field panels
To test:
1. Edit any page that can have topics added
2. Expand `Related` section and look at topics field panel
3. Make sure the string doesn't show up outside of admin
---
=> CIGI-755: Add (Archived) string to topic titles in admin

core/management/commands/update_topics.py
Management script that changes select topics to others
---
=> Merge topics

core/wagtail_hooks.py
resolves CIGIHub/cigi-tickets#600
Added admin menu item for about pages
---
=> CIGI-600: Add about pages admin menu

cigionline/static/js/components/ResearchContentListing.js, cigionline/static/pages/research_landing_page/index.js
resolves CIGIHub/cigi-tickets#667
---
=> CIGI-667: Add activity to research search table

config/nginx.conf.erb
=> Add nginx config for 2022 AR

signals/apps.py
=> CIGI-760d: add content type to slack notification

core/views.py
resolves CIGIHub/cigi-tickets#762
- Updated api date range
---
=> CIGI-762: Update date

articles/models.py
=> Revert anchor removal from footnotes

core/models.py, templates/articles/article_page.html, templates/events/event_page.html, templates/publications/publication_page.html
resolves CIGIHub/cigi-tickets#773
- Added function for previews only
- TODO: find out what is causing the root problem with previews
---
=> CIGI-773: Add new recommended content function for previews

core/models.py, templates/multimedia/multimedia_page.html
resolves CIGIHub/cigi-tickets#773
- Missing image due to not having `specific` call
- added specific as well as template code for multimedia pages
---
=> CIGI-773b: Add specific and variable for mm pages

features/models.py, home/models.py, templates/home/home_page.html
resolves CIGIHub/cigi-tickets#768
---
=> CIGI-768: Use revision created at instead of save to update cache

features/models.py, signals/apps.py
resolves CIGIHub/cigi-tickets#768
---
=> CIGI-768: Use signals to clear cloudflare home page cache

home/models.py
resolves CIGIHub/cigi-tickets#779
---
=> CIGI-779: Allow pages without author field to be retrieved for home page featured content

cigionline/settings/production.py, config/nginx.conf.erb
resolves CIGIHub/cigi-tickets#774
- Test admin path http basic auth protection
---
=> 774: Add http basic auth to production admin path

cigionline/settings/production.py, config/nginx.conf.erb
resolves CIGIHub/cigi-tickets#774
---
=> Test nginx

templates/base.html
Temporarily remove user bar until a solution is found to avoid cloudflare user bar caching.
---
=> Remove user bar

cigionline/static/css/cards/_card_small.scss, streams/blocks.py, templates/streams/ad_card_block.html
resolves CIGIHub/cigi-tickets#809
---
=> CIGI-809: Add ad card block

cigionline/static/css/admin.css
resolves CIGIHub/cigi-tickets#813
---
=> CIGI-813: Set admin rich text panel to break-all

cigionline/static/themes/space_series/css/_article_page.scss, cigionline/static/themes/space_series/css/_article_series_page.scss, cigionline/static/themes/space_series/index.js, templates/themes/space_series/article_series_page.html
resolves CIGIHub/cigi-tickets#758
- relocate properties under parent container; 
- add transition to series image
---
=> CIGI-758c: additional round of changes to space theme

cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_large.scss, cigionline/static/css/includes/_top_bar.scss, streams/blocks.py, templates/includes/top_bar_menu.html, templates/streams/home_page_row_most_popular_block.html
resolves CIGIHub/cigi-tickets#817
---
=> CIGI-817b: Change about page submenu to 4-columns

annual_reports/models.py, cigionline/static/css/cards/_card_social.scss, home/models.py, social/admin.py, social/models.py, social/tests.py, social/views.py, templates/home/home_page.html, templates/streams/twitter_card_block.html
resolves CIGIHub/cigi-tickets#819
---
=> CIGI-819: Add twitter intent to twitter cards

.sass-lint.yml, cigionline/static/themes/space_series/css/_article_page.scss, cigionline/static/themes/space_series/css/_article_series_page.scss, cigionline/static/themes/space_series/css/_multimedia_page.scss, cigionline/static/themes/space_series/index.js
=> CIGI-826: Update space series author font

cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_medium.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/cards/_card_social.scss, cigionline/static/css/cards/_card_tiny.scss, cigionline/static/pages/home_page/css/_home_page.scss, streams/blocks.py, templates/streams/expert_card_block_medium.html, templates/streams/expert_card_block_small.html, templates/streams/expert_card_block_tiny.html
resolves CIGIHub/cigi-tickets#829
---
=> CIGI-829: Add small, tiny expert cards

cigionline/static/css/cards/_card_large.scss, cigionline/static/css/cards/_card_medium.scss, cigionline/static/pages/home_page/css/_home_page.scss, templates/streams/publication_card_block_large.html
=> CIGI-810b: publication cards padding and font size adjustments

cigionline/static/css/cards/_card_medium.scss, cigionline/static/css/cards/_card_small.scss
=> CIGI-810c: pub card medium font size revert to standard

cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_large.scss, cigionline/static/css/cards/_card_medium.scss, cigionline/static/css/cards/_card_small.scss, templates/streams/article_card_block_large.html, templates/streams/article_card_block_medium.html, templates/streams/article_card_block_small.html, templates/streams/article_series_card_block_small.html, templates/streams/multimedia_card_block_medium.html, templates/streams/publication_card_block_large.html, templates/streams/publication_card_block_medium.html, templates/streams/publication_card_block_medium_vertical.html
Restructured CSS RE font:
- Change large/medium/medium-vertical/small to follow tiny's setup - default title font family inherited; articles the only type with research font family
- Title font size homogenized across different card types for each card sizes, with exceptions of events and experts
- Title font size also homogenized under small breakpoint for all card sizes.
- Added missing card size classes for some templates
=> CIGI-810d: font size alignment

articles/models.py, cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/components/SearchResultListingRow.scss, cigionline/static/css/components/SearchTable.scss, cigionline/static/css/global/_global.scss, cigionline/static/css/layout/_tables.scss, cigionline/static/js/components/ArticleSearchResultCard.js, cigionline/static/js/components/ArticleSeriesSearchResultCard.js, cigionline/static/js/components/EventSearchResultCard.js, cigionline/static/js/components/ExpertSearchResultCard.js, cigionline/static/js/components/MultimediaSearchResultCard.js, cigionline/static/js/components/PublicationSearchResultCard.js, cigionline/static/js/components/SearchResultCard.js, cigionline/static/js/components/SearchResultListingRow.js, cigionline/static/js/components/SearchTable.js, cigionline/static/pages/search_page/css/search_page.scss, cigionline/static/pages/search_page/index.js, core/models.py, core/templatetags/core_tags.py, events/models.py, people/models.py, search/templatetags/search_tags.py, streams/blocks.py, templates/search/search.html, templates/streams/event_card_block_large.html, templates/streams/event_card_block_medium.html, templates/streams/event_card_block_medium_vertical.html, templates/streams/event_card_block_small.html
resolves CIGIHub/cigi-tickets#832
---
=> CIGI-832: Style search page

cigionline/static/css/cards/_card_small.scss, cigionline/static/css/components/SearchTable.scss, cigionline/static/js/components/EventSearchResultCard.js, cigionline/static/pages/topic_page/css/topic_page.scss, cigionline/static/pages/topic_page/index.js, templates/research/topic_page.html
resolves CIGIHub/cigi-tickets#834
---
=> CIGI-834: Style topic page

cigionline/static/themes/space_series/css/_article_page.scss, templates/home/home_page.html
resolves CIGIHub/cigi-tickets#835
- Remove section
- TODO: remove model properties and queries if section will not be restored
---
=> CIGI-835: Remove featured experts section

templates/includes/people_person_leadership_tabs.html
resolves CIGIHub/cigi-tickets#836
---
=> CIGI-836: Swap leadership and board tabs

cigionline/static/css/global/_global.scss, cigionline/static/css/includes/_top_bar.scss, cigionline/static/index.js, templates/includes/top_bar.html
resolves CIGIHub/cigi-tickets#837
---
=> CIGI-837: Style full screen mobile dropdown 

cigionline/static/css/components/EventListCard.scss, cigionline/static/pages/event_list_page/css/_event_list_page.scss
- adjust padding on cards so that card items are centrally aligned in mobile
- change active tab border to a before element and positioned absolutely
=> CIGI-824c: events landing page padding and tab navigation border

cigionline/static/css/global/animations/_scroll.scss, cigionline/static/pages/home_page/css/_home_page.scss, templates/research/top_topics.html
resolves CIGIHub/cigi-tickets#840
---
=> CIGI-840: Implement trending issue scrolling animation 

.github/workflows/node.js.yml, .hound.yml, package-lock.json, package.json, requirements.txt
resolves CIGIHub/cigi-tickets#841
---
=> CIGI-841: Update vulnerable dependencies

cigionline/static/css/global/animations/_scroll.scss, cigionline/static/js/components/CardTextMore.js, cigionline/static/pages/home_page/css/_home_page.scss, templates/events/event_page.html, templates/research/top_topics.html
resolves CIGIHub/cigi-tickets#838
---
=> CIGI-838: Update trending issues scroll animation

cigionline/static/css/cards/_card_large.scss, cigionline/static/css/cards/_card_medium.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/global/_bootstrap_variables_overwrite.scss, cigionline/static/pages/home_page/css/_home_page.scss, templates/streams/article_card_block_large.html, templates/streams/home_page_row_block.html
Part 1 of CIGI-844: 
- Adjust some card spacing, title font size and card layouts
---
=> CIGI-844: Home page equal height rows

annual_reports/models.py, cigionline/static/css/global/_helpers.scss, cigionline/static/pages/annual_report_list_page/css/annual_report_list_page.scss, cigionline/static/pages/annual_report_list_page/index.js, templates/annual_reports/annual_report_list_page.html, templates/research/top_topics.html, templates/streams/annual_report_card_block.html
resolves CIGIHub/cigi-tickets#848
---
=> CIGI-848: Restyle annual reports page

cigionline/static/css/cards/_card_large.scss, cigionline/static/css/components/EventListingCard.scss, cigionline/static/css/components/EventSearchResultCard.scss, cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/EventSearchResultCard.js, cigionline/static/js/components/FeaturedEventCard.js, cigionline/static/pages/event_list_page/index.js, events/models.py
=> CIGI-824g: datetime processing streamlined

home/models.py, requirements.txt
resolves CIGIHub/cigi-tickets#858
- Use last published at field for home page template cache tags
---
=> CIGI-858: Fix home page feature list caching issue

cigionline/static/themes/ogbv/css/ogbv.scss, templates/includes/features/feature_content_large.html
resolves CIGIHub/cigi-tickets#861
- feature subtitle grouped with title
- ogbv feature main box title size up
---
=> CIGI-861b: updates to ogbv theme feature content template

templates/themes/ogbv/project_page.html
resolves CIGIHub/cigi-tickets#861
---
=> CIGI-861c: disclaimer wording change

cigionline/static/css/cards/_card_large.scss, cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/FeaturedEventCard.js, events/views.py, package-lock.json, templates/includes/cards/card_text_more.html, templates/streams/event_card_block_large.html, templates/streams/event_card_block_medium.html, templates/streams/event_card_block_medium_vertical.html, templates/streams/event_card_block_small.html
=> CIGI-863: Event landing page bug fixes

cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/FeaturedEventCard.js, events/views.py
=> CIGI-863b: minor fixes

articles/models.py, cigionline/static/css/cards/_card_medium.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/components/SearchResultListingRow.scss, cigionline/static/css/components/SearchTable.scss, cigionline/static/css/includes/_footer.scss, cigionline/static/css/includes/_hero_multimedia.scss, cigionline/static/css/includes/_topics.scss, cigionline/static/js/components/ArticleSearchResultCard.js, cigionline/static/js/components/EventSearchResultCard.js, cigionline/static/js/components/MultimediaCardLarge.js, cigionline/static/js/components/MultimediaCardXLarge.js, cigionline/static/js/components/MultimediaSearchResultCard.js, cigionline/static/js/components/PublicationSearchResultCard.js, cigionline/static/js/components/SearchResultListingRow.js, cigionline/static/js/components/SearchTable.js, cigionline/static/pages/article_landing_page/css/article_landing_page.scss, cigionline/static/pages/event_list_page/index.js, cigionline/static/pages/home_page/css/_home_page.scss, cigionline/static/pages/research_landing_page/index.js, cigionline/static/pages/search_page/css/search_page.scss, cigionline/static/pages/search_page/index.js, cigionline/static/pages/topic_page/index.js, core/models.py, search/views.py, templates/multimedia/multimedia_list_page.html, templates/research/top_topics.html, templates/streams/article_card_block_medium_large.html, templates/streams/article_series_card_block_small.html, templates/streams/event_card_block_large.html
resolves CIGIHub/cigi-tickets#862
- Fixed various search table issues 
---
=> CIGI-862: Standardize 3.0 search tables

cigionline/static/js/components/EventCalendar.js, cigionline/static/pages/event_list_page/css/_event_list_page.scss
=> CIGI-863a: Fix events calendar popover issue

cigionline/static/css/cards/_card_large.scss
=> CIGI-863d: events landing featured slider mobile padding top reduced

cigionline/static/pages/event_list_page/css/_event_list_page.scss
=> CIGI-863e: slider arrow position adjustment

cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/FeaturedEventCard.js, templates/includes/cards/card_text_more.html, templates/streams/event_card_block_large.html
=> CIGI-863f: event card cta conditioning adjustments

cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/FeaturedEventCard.js
=> CIGI-863g: private events with video link update cta button

cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/FeaturedEventCard.js, events/models.py, events/views.py
=> CIGI-863h: update "Watch Now" button URL

cigionline/settings/base.py, cigionline/urls.py
resolves CIGIHub/cigi-tickets#865
---
=> CIGI-865: Add sitemap

cigionline/static/js/components/SearchTableAnnualReports.js, cigionline/static/js/components/SearchTableExperts.js, cigionline/static/themes/big_tech/css/big_tech.scss, cigionline/static/themes/big_tech_s3/css/big_tech_s3.scss, templates/includes/experts_search_bar.html, templates/themes/big_tech/includes/top_bar.html, templates/themes/big_tech_s3/includes/top_bar.html, templates/themes/big_tech_s3/multimedia_series_page.html
resolves CIGIHub/cigi-tickets#866
---
=> CIGI-866: Update Big Tech theme headers

careers/models.py
resolves CIGIHub/cigi-tickets#868
- Sort job postings without a closing date to the end of the list
---
=> CIGI-868: Change careers page sort order

cigionline/static/css/cards/_card_large.scss, cigionline/static/css/includes/_hero_publication_book.scss, templates/includes/cards/card_text_date.html, templates/includes/cards/card_text_people.html, templates/streams/publication_card_block_large.html
resolves CIGIHub/cigi-tickets#872
add book border background colour and "edited by"
---
=> CIGI-872b: book pages updates

cigionline/static/css/cards/_card_large.scss, cigionline/static/css/cards/_card_medium.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/cards/_card_tiny.scss, cigionline/static/css/global/_mixins.scss, cigionline/static/css/includes/_top_bar.scss, cigionline/static/pages/media_landing_page/css/media_landing_page.scss, templates/articles/media_landing_page.html
resolves CIGIHub/cigi-tickets#876
---
=> CIGI-876: Style media landing page

cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_large.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/includes/_hero_publication_book.scss, streams/blocks.py, templates/includes/cards/card_button.html, templates/streams/event_card_block_large.html, templates/streams/event_card_block_medium.html, templates/streams/event_card_block_medium_vertical.html, templates/streams/event_card_block_small.html, templates/streams/publication_card_block_large.html, templates/streams/publication_card_block_medium.html, templates/streams/publication_card_block_medium_vertical.html, templates/streams/publication_card_block_small.html
=> CIGI-875: standardize card cta button sizes

cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_large.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/FeaturedEventCard.js, templates/streams/event_card_block_large.html, templates/streams/events_landing_event_card_block.html
=> CIGI-875b: standardize CTA buttons for event landing page

cigionline/static/css/cards/_card_small.scss, cigionline/static/pages/home_page/css/_home_page.scss
- for small publication cards on a row of 2 items, add button text on medium breakpoint
---
=> CIGI-875c: add button text for special cards at medium breakpoint 

cigionline/static/pages/publication_page/css/publication_page.scss, templates/publications/publication_page.html
resolves CIGIHub/cigi-tickets#872
---
=> CIGI-872c: Book page body and about-the-editor section styling

cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/cigionline.scss, cigionline/static/css/includes/_cta_button.scss, cigionline/static/css/includes/_hero_publication.scss, cigionline/static/css/includes/_hero_publication_book.scss, cigionline/static/js/components/EventListingCard.js, cigionline/static/js/components/FeaturedEventCard.js, cigionline/static/pages/home_page/css/_home_page.scss, templates/includes/cta_button.html, templates/includes/heroes/hero_publication.html, templates/streams/event_card_block_large.html, templates/streams/event_card_block_medium.html, templates/streams/event_card_block_medium_vertical.html, templates/streams/event_card_block_small.html, templates/streams/publication_card_block_large.html, templates/streams/publication_card_block_medium.html, templates/streams/publication_card_block_medium_vertical.html, templates/streams/publication_card_block_small.html
resolves CIGIHub/cigi-tickets#878
- update to cta button
- social links on left
- set colours of items according to design
---
=> CIGI-878: publication page styling

templates/streams/event_card_block_medium.html, templates/streams/event_card_block_medium_vertical.html, templates/streams/event_card_block_small.html
=> CIGI-875d: event card text meta vertically stack when cta button is present

cigionline/static/css/includes/_recommended.scss, streams/blocks.py, templates/includes/recommended.html, templates/streams/card_block_tiny.html
resolves CIGIHub/cigi-tickets#874
---
=> CIGI-874: Style content page recommended section

cigionline/static/css/cards/_card.scss, cigionline/static/css/cards/_card_medium.scss, cigionline/static/css/cards/_card_small.scss, cigionline/static/css/includes/_cta_button.scss, streams/blocks.py, templates/includes/heroes/hero_publication.html, templates/includes/heroes/hero_publication_book.html, templates/streams/publication_card_block_medium.html, templates/streams/publication_card_block_medium_vertical.html
- Add landscape image class
- Move stacking button styling to landscape image class
- remove comments
- bring down button size a bit further
---
=> CIGI-875e: Add landscape image class for Publication Cards

cigionline/static/css/cigionline.scss, cigionline/static/css/includes/_contact_info.scss, cigionline/static/css/layout/_forms.scss, cigionline/static/css/streams/_contact_email_block.scss, cigionline/static/pages/contact_page/css/_contact_page.scss, cigionline/static/pages/contact_page/index.js, templates/contact/contact_page.html, templates/includes/contact_info.html, templates/streams/contact_email_block.html, webpack.config.js
resolves CIGIHub/cigi-tickets#886
---
=> CIGI-886: Style contact page

.github/workflows/django.yml, cigionline/static/css/global/_variables.scss, cigionline/static/themes/dph/css/_basic_page.scss, templates/streams/persons_list_block.html, templates/themes/dph/basic_page.html
resolves CIGIHub/cigi-tickets#899
---
=> CIGI-899b: Digital Policy Hub styling updates

signals/apps.py
resolves CIGIHub/cigi-tickets#911
---
=> CIGI-911: replace PageRevision imports

careers/models.py, core/models.py, menus/models.py
resolves CIGIHub/cigi-tickets#906
---
=> CIGI-906: update title field panels to re-establish automatic slug generation

annual_reports/tests.py, articles/tests.py, careers/tests.py, contact/tests.py, core/tests.py, events/tests.py, home/tests.py, multimedia/tests.py, newsletters/tests.py, people/tests.py, promotions/tests.py, publications/tests.py, research/tests.py, subscribe/tests.py
resolves CIGIHub/cigi-tickets#910
> WagtailPageTestCase is the base testing class and is now recommended over using WagtailPageTests
- Switch to the new base testing class
---
=> CIGI-910: Replace class in tests

templates/base.html
resolves CIGIHub/cigi-tickets#913
---
=> CIGI-913: Add meta pixel code

templates/contact/contact_page.html
resolves CIGIHub/cigi-tickets#916
- Removed contact form
---
=> CIGI-916: Remove contact form

signals/apps.py
resolves CIGIHub/cigi-tickets#918
---
=> CIGI-918: notification module misfiring

cigionline/static/js/components/SearchTable.js, cigionline/urls.py, core/views.py
resolves CIGIHub/cigi-tickets#915
- Search tables retrieve a list of all publishing years based on query of content pages
- Year filter will only display years that have content
---
=> CIGI-915: Update search tables to retrieve a list of all publishing years

cigionline/static/index.js, cigionline/static/js/components/AnnualReportListing.js, cigionline/static/js/components/EventListing.js, cigionline/static/js/components/ExpertContentListing.js, cigionline/static/js/components/ProjectContentListing.js, cigionline/static/js/components/PublicationListing.js, cigionline/static/js/components/PublicationListingSeries.js, cigionline/static/js/components/ResearchContentListing.js, cigionline/static/js/components/SearchTable.js, cigionline/static/js/components/TopicContentListing.js, templates/annual_reports/annual_report_page.html, templates/articles/article_page.html, templates/includes/features/feature_content_cta.html, templates/includes/features/feature_event.html, templates/includes/features/feature_expert_short.html, templates/includes/features/feature_publication_teaser.html, templates/includes/heroes/hero_publication.html, templates/includes/swiper.html, templates/publications/publication_page.html, templates/streams/additional_file_block.html, templates/streams/survey_findings_country_block.html, templates/subscribe/subscribe_page.html, templates/themes/ogbv/project_page.html
resolves CIGIHub/cigi-tickets#919
- Added custom pixel tracking script to CTA buttons across site
---
=> CIGI-919: Add Meta pixel tracking to CTA buttons

requirements.txt, streams/blocks.py
resolves CIGIHub/cigi-tickets#920
(currently on staging)
- some dependencies updated
- `get_template()` method in Blocks updated to include the new value argument: https://docs.wagtail.org/en/stable/releases/5.2.html#block-get-template-now-accepts-a-value-argument
---
=> CIGI-920: upgrade wagtail from 5.1.3 to 5.2

menus/models.py, menus/wagtail_hooks.py
resolves CIGIHub/cigi-tickets#928
---
=> CIGI-928: Allow editing of menu items

templates/newsletters/newsletter_html.html
resolves CIGIHub/cigi-tickets#929
---
=> CIGI-929: Update twitter brand icon to x

cigionline/static/themes/freedom_of_thought/css/fot.scss, cigionline/static/themes/freedom_of_thought/index.js, templates/themes/freedom_of_thought/project_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#933
Template and styling for Freedom of Thought topbar and hero
---
=> CIGI-933: Custom theme for Freedom of Thought project page

cigionline/static/pages/project_page/index.js, research/models.py, templates/research/project_page.html
resolves CIGIHub/cigi-tickets#934
- Added flag that disables search table rendering if the project page is not tagged to any content pages
---
=> CIGI-934: Hide search tables on project pages with no tagged pages

cigionline/static/pages/home_page/css/_home_page.scss, cigionline/static/pages/subscribe_page/css/subscribe_page.scss, subscribe/models.py, templates/home/home_page.html, templates/subscribe/subscribe_page_landing.html
resolves CIGIHub/cigi-tickets#935
- Add home page subscription header
- Adjust subscribe page wording
---
=> CIGI-935: Implement home page newsletter header

cigionline/static/css/streams/_persons_list_block.scss, cigionline/static/themes/dph/css/_basic_page.scss, templates/themes/dph/basic_page.html
resolves CIGIHub/cigi-tickets#938
- Moved disclaimer about fellows to bottom of page
- Updated contact email
---
=> CIGI-938: Adjust DPH landing page text

templates/newsletters/newsletter_html.html
resolves CIGIHub/cigi-tickets#942
---
=> CIGI-942: Remove Facebook logo from newsletter tempalte

streams/blocks.py
resolves CIGIHub/cigi-tickets#951
- Add sort for publications list block auto-populating function
---
=> CIGI-951: Sort publications list block auto-populating by date

cigionline/static/css/global/_variables.scss, cigionline/static/themes/accents/css/accents.scss, cigionline/static/themes/accents/index.js, package-lock.json, templates/themes/accents/article_page.html, webpack.config.js
resolves CIGIHub/cigi-tickets#952
- added accents theme for article pages
- demo page on staging: https://staging.cigionline.org/articles/generative-ai-risks-further-atomizing-liberal-democratic-societies/
- consult designs for a font closer to CIGI default, perhaps Proxima Nova?
- maybe expand to other page types in the future - lower priority
---
=> CIGI-952: Theme to support accents

cigionline/static/themes/ges/css/ges.scss, templates/streams/ges_data_block.html, templates/streams/ges_highlights_block.html, templates/streams/ges_slide_deck_block.html
resolves CIGIHub/cigi-tickets#959
---
=> CIGI-959b: Add links to images on GES page

people/tests.py, publications/tests.py, research/tests.py
resolves CIGIHub/cigi-tickets#961
---
=> CIGI-961: Fix tests

cigionline/static/themes/ges/css/ges.scss
resolves CIGIHub/cigi-tickets#965
- Fix minor margin issue
---
=> CIGI-965b: Fix minor spacing issue

templates/articles/article_series_list_page.html
resolves CIGIHub/cigi-tickets#966
- Add body section
---
=> CIGI-966b: Add body to article series list page

cigionline/settings/production.py
resolves CIGIHub/cigi-tickets#970
- Increase timeout to 300
---
=> CIGI-970: Increase elasticsearch backend timeout

cigionline/static/css/global/_variables.scss, cigionline/static/css/includes/_top_bar.scss, cigionline/static/css/includes/features/_feature_content.scss, cigionline/static/css/includes/features/_feature_event.scss, cigionline/static/index.js, templates/includes/features/feature_content_cta.html, templates/includes/features/feature_publication_teaser.html, templates/includes/footer.html, templates/includes/promotion_block.html, templates/includes/top_bar.html, templates/themes/space_series/includes/top_bar.html
resolves CIGIHub/cigi-tickets#971
- Fixed accessibility issues outlined at: https://axe.deque.com/axe-devtools/tests/19a34fb9-bc7b-4287-9460-abb06da091f5?configWCAGLevel=wcag21aa&configAccessibilityStandard=wcag21aa&configBestPractices=disabled&configNeedsReview=disabled
---
=> CIGI-971: Fix home page accessibility issues

articles/migrations/0044_alter_article_series_article_page_type.py, articles/views.py, cigionline/static/js/components/SearchResultListing.js, cigionline/static/pages/article_landing_page/index.js, cigionline/static/pages/publication_list_page/index.js, cigionline/static/pages/search_page/index.js, cigionline/urls.py
resolves CIGIHub/cigi-tickets#969
- use `/api/article_series_article_pages/` to extract a summary of article series article pages and their types before and after migration
- migrate to apply change
- what changes do we have to make regarding the search table?
---
=> CIGI-969: update article_type of article series article pages

articles/models.py, articles/tests.py, publications/models.py, publications/tests.py
resolves CIGIHub/cigi-tickets#981
- Added article type page to publication list page allowed child types
- Fixed tests
---
=> CIGI-981: Allow article type page to be children of publication list page

cigionline/static/css/global/_variables.scss, cigionline/static/css/includes/_swiper.scss, cigionline/static/css/includes/features/_feature_content.scss
resolves CIGIHub/cigi-tickets#973
- Added new variables for primary colour on grey and black backgrounds
---
=> CIGI-973: Fix publications landing page accessibility issues

cigionline/static/js/components/Paginator.js, cigionline/static/js/components/ProjectContentListing.js, cigionline/static/js/components/PublicationListing.js, cigionline/static/js/components/PublicationListingSeries.js, cigionline/static/js/components/ResearchContentListing.js, cigionline/static/js/components/SearchTable.js, cigionline/static/js/components/TopicContentListing.js
resolves CIGIHub/cigi-tickets#972
Fix issues outlined in: https://axe.deque.com/axe-devtools/tests/19a34fb9-bc7b-4287-9460-abb06da091f5?configWCAGLevel=wcag21aa&configAccessibilityStandard=wcag21aa&configBestPractices=disabled&configNeedsReview=disabled
---
=> CIGI-972: Fix Research landing page accessibility issues

cigionline/static/js/components/ResearchContentListing.js, cigionline/static/js/components/SearchResultListing.js, cigionline/static/pages/article_landing_page/index.js, cigionline/static/pages/publication_list_page/index.js, cigionline/static/pages/research_landing_page/index.js, cigionline/static/pages/search_page/index.js
resolves CIGIHub/cigi-tickets#983
- Added icon for essays in research search table
- Renamed filter in publications search table
---
=> CIGI-983: Fix essay not correctly displaying on research and publications search tables

people/management/commands/clear_all_experts_cache.py
resolves CIGIHub/cigi-tickets#977
- Add management command to clear all_experts cache to be used with scheduler to clear cache after updating index
---
=> CIGI-977: Add command to clear all experts cache

templates/includes/footer.html, templates/newsletters/newsletter_html.html
resolves CIGIHub/cigi-tickets#987
added to:
- footer
- newsletter
---
=> CIGI-987: add Instagram icons

templates/includes/footer.html, templates/includes/heroes/hero_event.html, templates/includes/swiper.html, templates/includes/top_bar.html, templates/people/person_page.html, templates/streams/ges_data_block.html, templates/streams/ges_highlights_block.html, templates/streams/ges_raw_data_block.html, templates/streams/ges_slide_deck_block.html, templates/subscribe/subscribe_page_landing.html, templates/themes/ogbv/project_page.html, templates/themes/space_series/includes/top_bar.html
resolves CIGIHub/cigi-tickets#990
- add rel="noopener noreferrer" to external links that open in a new page
- ignored instances where link is internal (e.g. to download a pdf')
---
=> CIGI-990: security updates to external links that open in a new page

cigionline/static/js/components/TwentiethPageSlide1Content.js, streams/blocks.py, templates/includes/promotion_block.html, templates/includes/social_links.html, templates/includes/social_links_square.html, templates/includes/top_bar.html, templates/includes/twentieth_page_top_bar.html, templates/people/person_page.html, templates/subscribe/subscribe_page_landing.html, templates/themes/after_covid_series/streams/opinion_block_quote_block.html, templates/themes/cyber_series/article_page.html, templates/themes/data_series/article_page.html, templates/themes/data_series/includes/social_links.html, templates/themes/indigenous_lands_series/article_page.html, templates/themes/indigenous_lands_series/article_series_page.html, templates/themes/innovation_series/article_page.html, templates/themes/longform/article_page.html, templates/themes/longform_2/article_page.html, templates/themes/longform_2_dark_mode/article_page.html, templates/themes/platform_governance_series/article_page.html, templates/themes/platform_governance_series/article_series_page.html, templates/themes/space_series/article_page.html, templates/themes/space_series/article_series_page.html, templates/themes/space_series/includes/top_bar.html, templates/themes/women_and_trade_series/article_page.html, templates/themes/women_and_trade_series/includes/social_links.html, templates/themes/wto_series/includes/social_links.html
resolves CIGIHub/cigi-tickets#989
---
=> CIGI-989: Change twitter.com to x.com

cigionline/static/css/includes/features/_feature_content_medium.scss, templates/includes/features/feature_content_medium.html
resolves CIGIHub/cigi-tickets#994
- Add gif support to template
- Force aspect ratio 
---
=> CIGI-994: Add gif support for medium features

core/templatetags/theme_tags.py, streams/blocks.py, templates/themes/dph/streams/page_publications_list_block.html
resolves CIGIHub/cigi-tickets#996
- Add template tag to automatically display term based on publishing date
---
=> CIGI-996: Add automatic term label to dph working papers page

core/models.py, search/search.py
resolves CIGIHub/cigi-tickets#997
---
=> CIGI-997: exclude working papers from being recommended

core/templatetags/theme_tags.py, templates/themes/dph/streams/page_publications_list_block.html
resolves CIGIHub/cigi-tickets#999
- Decrease year by 1 for fall term
- Add override in template
---
=> CIGI-999: Fix DPH term logic

research/models.py
resolves CIGIHub/cigi-tickets#1010
---
=> CIGI-1010: Exclude CIGI in the News from auto featuring on topic and country pages

events/models.py
resolves CIGIHub/cigi-tickets#1011
- `values_list` method in existing query doesn't work in preview
- continue using existing query for the live page
- add alternative query for preview only
---
=> CIGI-1011: Fix featured events on events landing page not displaying in preview

cigionline/static/themes/policy_prompt/css/_multimedia_series_page.scss, templates/themes/policy_prompt/includes/footer.html, templates/themes/policy_prompt/multimedia_series_page.html
- Use dynamic subscribe buttons
- Removed google podcasts
- Styling updates
---
=> CIGI-1013: Policy Prompt updates

templates/themes/policy_prompt/includes/footer.html
=> CIGI-1013: Remove terms of use link in footer

cigionline/static/themes/special_opinions/css/_article_body.scss
resolves CIGIHub/cigi-tickets#1015
---
=> CIGI-1015: Special opinions theme adjustments

templates/themes/policy_prompt/multimedia_page.html, templates/themes/policy_prompt/multimedia_series_page.html
=> CIGI-1013: Update episode page dropdowns

cigionline/static/themes/policy_prompt/css/_multimedia_page.scss, templates/themes/policy_prompt/multimedia_page.html
=> CIGI-1013: Add share links to episode pages

templates/research/project_page.html, templates/themes/freedom_of_thought/project_page.html
resolves CIGIHub/cigi-tickets#1017
---
=> CIGI-1017: Program/project page featured section xlarge slot

templates/themes/policy_prompt/multimedia_series_page.html
=> CIGI-1013: Hide unpublished episodes

templates/themes/policy_prompt/multimedia_series_page.html
=> CIGI-1013: Hide section if no episodes are published

cigionline/static/themes/policy_prompt/css/_multimedia_page.scss, templates/themes/policy_prompt/multimedia_page.html, templates/themes/policy_prompt/multimedia_series_page.html
- Hide sections if fields are empty
---
=> CIGI-1013: Policy prompt episode page updates

templates/themes/policy_prompt/multimedia_page.html
resolves CIGIHub/cigi-tickets#1022
- Add default image to recommended section items
---
=> CIGI-1022: Add default image PP recommended section items

templates/themes/policy_prompt/multimedia_page.html
resolves CIGIHub/cigi-tickets#1023
- Add podcast_live variable to episode page footer
---
=> CIGI-1023: Update footer live variable

cigionline/static/themes/policy_prompt/css/_multimedia_page.scss, templates/themes/policy_prompt/multimedia_page.html
resolves CIGIHub/cigi-tickets#2024
- Added accordion functionality
---
=> CIGI-2024: Add accordion to PP multimedia page transcript

templates/base.html
resolves CIGIHub/cigi-tickets#1026
- Removed self-closing tags in meta elements
---
=> CIGI-1026: Remove self-closing tags in base.html

cigionline/static/themes/policy_prompt/index.js, multimedia/models.py, templates/themes/policy_prompt/multimedia_page.html
resolves CIGIHub/cigi-tickets#1025
Added automatic parsing of Policy Prompt transcript
To test:
- Add a single "accordion" transcript block to the transcript field
- Make sure the text is formatted like this:
Vass Bednar (host):
Text
Text
Paul Samson (host):
Text
Text
Guest name (guest):
Text
Text
---
=> CIGI-1025: Automatically parse transcript into html

events/models.py, templates/themes/policy_prompt/multimedia_page.html
resolves CIGIHub/cigi-tickets#1030
---
=> CIGI-1030: Recommended content preview handling for Policy Prompt MM pages

cigionline/static/themes/dph/css/_basic_page.scss
resolves CIGIHub/cigi-tickets#1031
Changed "the" in "About the Author" to lowercase 
---
=> CIGI-1031: DPH about the author heading change

cigionline/static/themes/ges/css/ges.scss
resolves CIGIHub/cigi-tickets#1032
- change hero section subtitle colour to black to contrast against new branding image
---
=> CIGI-1032: GES project page branding update

cigionline/static/js/components/AnnualReportListing.js, cigionline/static/pages/annual_report_list_page/css/annual_report_list_page.scss
resolves CIGIHub/cigi-tickets#1002
- Added a little bit of padding-bottom to AR list page swiper
- Adjusted download buttons to center icons
---
=> CIGI-1002: Adjust AR list page spacing and buttons

templates/newsletters/newsletter_html.html
resolves CIGIHub/cigi-tickets#1033
- Added icons to mailchimp and newsletter template
---
=> CIGI-1033: Add substack and medium icons to newsletter footer

cigionline/static/themes/ges/css/ges.scss
resolves CIGIHub/cigi-tickets#1036
- remove background colour of the highlights block
---
=> CIGI-1036: GES minor branding change

cigionline/static/themes/ges/css/ges.scss, templates/themes/freedom_of_thought/project_page.html, templates/themes/ges/project_page.html
resolves CIGIHub/cigi-tickets#1038
- add a featured section to the GES program page
---
=> CIGI-1038: GES featured section

cigionline/static/themes/ges/css/ges.scss
resolves CIGIHub/cigi-tickets#1038
- fix misplaced styling
---
=> CIGI-1038b: GES feature section style fix

templates/themes/ges/project_page.html
resolves CIGIHub/cigi-tickets#1038
---
=> CIGI-1038c: add cta pdf to main spot of GES featured section

cigionline/middleware.py, cigionline/settings/base.py
resolves CIGIHub/cigi-tickets#1039
---
=> CIGI-1039: Add basic auth middleware for think7 domain

publications/models.py
=> Nonetype fix for Quick Insight

cigionline/static/pages/think7/project_page/css/project_page.scss
resolves CIGIHub/cigi-tickets#1040
---
=> CIGI-1040c: Chair label size update

cigionline/static/pages/think7/css/_header.scss, contact/tests.py, core/tests.py, events/tests.py, home/models.py, people/tests.py, publications/tests.py, research/tests.py, templates/think7/includes/footer.html, templates/think7/includes/top_bar.html, templates/think7/think7_abstract_page.html, uploads/views.py
resolves CIGIHub/cigi-tickets#1044
- remove buttons from header and footer
- remove submission form from abstract submission page
---
=> CIGI-1044: Remove abstract submission button from header and footer

templates/streams/podcast_guest_block.html
resolves CIGIHub/cigi-tickets#1049
- Added check for podcast_guest_block guest_page logic in template
---
=> CIGI-1049: Fix podcast_guest block null pointer

cigionline/static/themes/dph/css/_basic_page.scss, templates/themes/dph/basic_page.html, templates/themes/dph/includes/top_bar.html
resolves CIGIHub/cigi-tickets#1052
- Update banner copy
- Increase hero section top padding for small screens
---
=> CIGI-1052: Update dph banner copy

cigionline/static/themes/ogbv/css/ogbv.scss, templates/themes/ogbv/project_page.html
resolves CIGIHub/cigi-tickets#1055
- Move video block to resources section
- Add image block to resources section
- Add separator line between video and image
---
=> CIGI-1055: Adjust ogbv project page layout

cigionline/static/themes/ogbv/css/ogbv.scss, templates/themes/ogbv/project_page.html
resolves CIGIHub/cigi-tickets#1055
-Add team members section to OBGV project page
---
=> CIGI-1055a: Add team members section to OBGV project page

events/views.py
resolves CIGIHub/cigi-tickets#1058
---
=> CIGI-1058: exclude T7 events from CIGI event calendar

core/models.py
resolves CIGIHub/cigi-tickets#1059
---
=> CIGI-1059: exclude t7 from recommended content

cigionline/urls.py, subscribe/views.py
resolves CIGIHub/cigi-tickets#1063
---
=> CIGI-1063: subscribe page routing fix

templates/think7/event_page.html, templates/think7/event_page_no_base.html
resolves CIGIHub/cigi-tickets#1065
---
=> CIGI-1065: T7 event page update wording of agenda attachment

cigionline/static/pages/think7/publication_list_page/css/publication_list_page.scss, core/templatetags/core_tags.py, templates/think7/project_page.html, templates/think7/publication_list_page.html
resolves CIGIHub/cigi-tickets#1066
---
=> CIGI-1066: update T7 publications display

cigionline/static/pages/think7/project_page/css/project_page.scss, cigionline/static/pages/think7/publication_list_page/css/publication_list_page.scss
resolves CIGIHub/cigi-tickets#1066
---
=> CIGI-1066b: colour change on T7 publication type display

cigionline/static/pages/person_page/css/person_page.scss, people/models.py, templates/people/person_page.html
resolves CIGIHub/cigi-tickets#1077
- Added external profile disclaimer
- Removed image for external profiles
---
=> CIGI-1077: Add external profile disclaimer and hide image

templates/themes/digital_finance/event_page.html
resolves CIGIHub/cigi-tickets#1080
---
=> CIGI-1080b: update end times

cigionline/static/pages/digital_finance/css/_event_page.scss
resolves CIGIHub/cigi-tickets#1083
---
=> CIGI-1083: Update Digifincon bg colour

cigionline/static/pages/digital_finance/css/_event_page.scss
resolves CIGIHub/cigi-tickets#1100
- Update bg colour to FFF3E3
---
=> CIGI-1100: Update bg colour

cigionline/static/themes/policy_prompt/css/_multimedia_series_page.scss, cigionline/static/themes/policy_prompt/index.js, multimedia/models.py, templates/themes/policy_prompt/multimedia_page.html, templates/themes/policy_prompt/multimedia_series_page.html
resolves CIGIHub/cigi-tickets#1115
---
=> CIGI-1115: Implement Policy Prompt seasons 

home/models.py
resolves CIGIHub/cigi-tickets#1116
---
=> CIGI-1116: Hide digifin policy briefs from home page
